### ISSUE TITLE
Server Rebooting Every 10-15 Seconds

### ISSUE THREAD

**Issue by Sandman007** [L-EARN/NoCheatZ-4#10]
Hey me again :)

Sorry to keep bothering you but my server keeps rebooting.

Spammed in NoCheatz Log

`05/24/16 15:37:03 [Server Tick #129] PLAYING ON A NEW MAP : am_snow_cbg
05/24/16 15:37:59 [Server Tick #129] PLAYING ON A NEW MAP : am_snow_cbg
05/24/16 15:38:05 [Server Tick #740] SourceTV not detected. Reloading the map ...
05/24/16 15:38:06 [Server Tick #129] PLAYING ON A NEW MAP : am_snow_cbg
05/24/16 15:38:19 [Server Tick #0] [NoCheatZ 4.0 Alpha] WARNING : Unexpected virtual table value in VirtualTableHook. Another plugin might be in conflict.`

How do I know which plugin is conflicting?

Plugins List:
Pastebin for better readability: http://pastebin.com/fxUGKf3n
`[SM] Listing 60 plugins:
  01 "DR.API JOIN SOUNDS" (1.0.1) by Dr. Api
  02 "[CSGO] Hs Impact Effect" (1.5) by TonyBaretta
  03 "Basic Chat" (1.7.3-dev+5298) by AlliedModders LLC
  04 "Rock The Vote Extended" (1.10.0) by Powerlord and AlliedModders LLC
  05 "[Store] Player size" (1.0.0) by Franc1sco steam: franug
  06 "[Store] Gifting Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  07 <Error> "[Store] Chat Color" (1.2) by Panduh, csgo fix by wyd3x
  08 "[Store] Equipment" (1.1-alpha) by alongub
  09 "[Store] Titles" (1.1-alpha) by alongub
  10 "Basic Votes" (1.7.3-dev+5298) by AlliedModders LLC
  11 "CS:GO Multi1v1: headshot round addon" (1.0.0) by Bara
  12 "[Store] Shop Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  13 "[Store] Name Colors" (1.1) by Panduh
  14 "CS:GO Multi1v1: flashbangs addon" (1.1.3) by splewis
  15 "Map Nominations" (1.7.3-dev+5298) by AlliedModders LLC
  16 "Basic Commands" (1.7.3-dev+5298) by AlliedModders LLC
  17 "SM CS:GO Franug Knives" (1.5) by Franc1sco franug
  18 "Map Nominations Extended" (1.10.0) by Powerlord and AlliedModders LLC
  19 "SQL Admins (Threaded)" (1.7.3-dev+5298) by AlliedModders LLC
  20 "[Store] Kill Awards" (1.1.1-alpha) by eXemplar
  21 "[Store] Logging Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  22 "Admin Help" (1.7.3-dev+5298) by AlliedModders LLC
  23 "Player Commands" (1.7.3-dev+5298) by AlliedModders LLC
  24 "Admin File Reader" (1.7.3-dev+5298) by AlliedModders LLC
  25 "[Store] Loadouts Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  26 "Fun Commands" (1.7.3-dev+5298) by AlliedModders LLC
  27 "Advertisements" (2.0.2) by Tsunami
  28 "RankMe" (3.0.0) by lok1
  29 "MapChooser Extended" (1.10.2) by Powerlord, Zuko, and AlliedModders LLC
  30 "Basic Comm Control" (1.7.3-dev+5298) by AlliedModders LLC
  31 "Anti-Flood" (1.7.3-dev+5298) by AlliedModders LLC
  32 "Fun Votes" (1.7.3-dev+5298) by AlliedModders LLC
  33 "Basic Ban Commands" (1.7.3-dev+5298) by AlliedModders LLC
  34 "[Store] Distributor Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  35 "Mapchooser Extended Sounds" (1.10.2) by Powerlord
  36 "[Multi-1v1] Challenge" (1.2) by Headline
  37 "Basic Info Triggers" (1.7.3-dev+5298) by AlliedModders LLC
  38 "AFK Manager" (4.0.5) by Rothgar
  39 "TOG Clan Tags" (1.5) by That One Guy
  40 "Reserved Slots" (1.7.3-dev+5298) by AlliedModders LLC
  41 "[Store] Inventory Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  42 "[Store] Tracers" (1.0.1) by Franc1sco steam: franug
  43 "Admin loggin" (1.0) by vIr-Dan
  44 "[Store] Refunds Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  45 "High Ping Kicker - Lite Edition" (1.0.0.1) by Liam
  46 "Weddings" (2.0.4) by Dr. O
  47 "Simple Chat Processor (Redux)" (1.1.5) by Simple Plugins, Mini
  48 "Admin Menu" (1.7.3-dev+5298) by AlliedModders LLC
  49 "Client Preferences" (1.7.3-dev+5298) by AlliedModders LLC
  50 "CS:GO Multi1v1: knife round addon" (1.1.3) by splewis
  51 "Sound Commands" (1.7.3-dev+5298) by AlliedModders LLC
  52 "SM CS:GO Weapon Paints" (2.8.4 public version) by Franc1sco franug
  53 "[Store] Core Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  54 "SQL Admin Manager" (1.7.3-dev+5298) by AlliedModders LLC
  55 "RandomCycle" (1.7.3-dev+5298) by AlliedModders LLC
  56 "CS:GO Multi1v1" (1.1.3) by splewis
  57 "Quake Sounds v3" (3.4.3) by Spartan_C001
  58 "[Store] Backend Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  59 "Jukebox" (0.5.5.0) by SirLamer
  60 "Plugin Manager" (1.1.0) by R-Hehl
Load Errors:
[Store] Chat Color: Error detected in plugin startup (see error logs)
`

Thanks
Sandman007

**Comment by Sandman007** [comment]
Is it because I do not have SourceTV installed? If So how do i install it?

**Comment by L-EARN** [comment]
The SourceTv is added automatically.
The problem is when you want to have spectators on it, you must open the port (Usually this is the port of your server + 1). Use the `tv_port` convar to know.

But this is not your problem here.
Here is your problem : Another (Or others) plugins are hooking the same function(s) we need. And when the hooks are not sorted in time, unhooks will replace functions in a bad way that will make plugin A actually call plugin B code (instead of engine code) when plugin B is probably not ready (because it thinks it is unhooked) -> crash -> reboot

One way of behing more stable is to never unhook/rehook or only when the plugin is unloaded ...
This will take some time to modify this behavior.

**Comment by L-EARN** [comment]
Please [download this branch](https://github.com/L-EARN/NoCheatZ-4/tree/issue-10-test-0), extract it in another directory, compile it and test if this solve the issue.
Don't forget to copy the `server-plugin/SourceSdk` directory from the old project directory to the new directory you make.

Thanks.

**Comment by Sandman007** [comment]
I didn't have any issues compiling the last several builds you gave me yesterday but today I  can not seem to figure out how to pull from your new test branch. (TBH I am still kinda of new to GitHub). Can you give me the git clone git://URL please?

**Comment by L-EARN** [comment]
You can specify the name of the branch using -b
Prefer putting it in another directory to avoid messing up with the _stable_ version.

```
git clone -b issue-10-test-0 --single-branch https://github.com/L-EARN/NoCheatZ-4 your-new-folder
cd your-new-folder
git submodule update --init
```

**Comment by L-EARN** [comment]
If you want there is another test that implements a HookGuard.

git clone -b issue-10-test-1 --single-branch https://github.com/L-EARN/NoCheatZ-4 your-new-folder
cd your-new-folder
git submodule update --init

**Comment by Sandman007** [comment]
Thank you! I am currently migrating my 2 CSGO Servers/Web Servers and MySQL Databases onto a new Server. This is gonna take me a few days. I will get back to you this weekend. Thanks!

**Comment by L-EARN** [comment]
This issue is now considered fixed after some tests I made in compatibility with SourceMod.

The branchs issue-10-test-0 and issue-10-test-1 will be removed.

If you still have problems after using the latest commit from the master branch, feel free to open another issue.

To use the latest commit, just clone the code again as explained in the readme or `git pull` in the NoCheatZ-4 directory.

Thanks.
