### ISSUE TITLE
AutoTVRecord crashing on unload at end of map

### ISSUE THREAD

**Issue by blackhawk74** [L-EARN/NoCheatZ-4#100]
Hello,

I've been running this particular CS:GO server for months without a single crash, I added Beta r3 to the server last night and am experiencing frequent server crashes, unfortunately without much logging. I will add more information as I can. It appears it might be after a player connect/team switch? Not sure at the moment and will be disabling certain modules to see if that helps the matter. I also run SMAC, if that may cause any conflicts in regards to crashes.

Some ncz logs (note that am_plain2 is the default start map of the server): http://pastebin.com/xXnG5ucY

The ending of a default server log ends quite abruptly:

```
L 10/15/2016 - 13:34:43: Team "TERRORIST" triggered "SFUI_Notice_Terrorists_Win" (CT "0") (T "0")
L 10/15/2016 - 13:34:43: Team "CT" scored "0" with "10" players
L 10/15/2016 - 13:34:43: Team "TERRORIST" scored "0" with "9" players
L 10/15/2016 - 13:34:43: World triggered "Round_End"
L 10/15/2016 - 13:34:45: "Galaxy[H]<29><STEAM_1:1:xx>" swit
```

```
Systems list :
RadarHackBlocker (Disabled by config.ini)
Commands : Enable - Disable - Verbose
AutoTVRecord (Running)
Commands : Enable - Disable - Verbose
ValidationTester (Disabled by config.ini)
Commands : Enable - Disable - Verbose
SpeedTester (Running)
Commands : Enable - Disable - Verbose
SpamConnectTester (Running)
Commands : Enable - Disable - Verbose
SpamChangeNameTester (Running)
Commands : Enable - Disable - Verbose
AutoAttackTester (Running)
Commands : Enable - Disable - Verbose
JumpTester (Disabled manually)
Commands : Enable - Disable - Verbose
EyeAnglesTester (Running)
Commands : Enable - Disable - Verbose
ConVarTester (Disabled manually)
Commands : Enable - Disable - Verbose - AddRule - RemoveRule - ResetRules
ConCommandTester (Running)
Commands : Enable - Disable - Verbose
WallhackBlocker (Disabled manually)
Commands : Enable - Disable - Verbose
BhopBlocker (Disabled manually)
Commands : Enable - Disable - Verbose
BadUserCmdBlocker (Disabled manually)
Commands : Enable - Disable - Verbose
AntiSmokeBlocker (Disabled manually)
Commands : Enable - Disable - Verbose
AntiFlashbangBlocker (Running)
Commands : Enable - Disable - Verbose
BanRequest (Static)
Commands : Verbose - CanKick - CanBan
Logger (Static)
Commands : Verbose
```

**Comment by blackhawk74** [comment]
Crash just happened to me as the map ended (scoreboard showed up right before map change), ~20 people in the server.

Only active modules were:
AutoTVRecord
SpeedTester
AutoAttackTester
EyeAnglesTester

**Comment by L-EARN** [comment]
Hi,

The Beta r3 was not tested with metamod or sourcemod.
There is compat issues between ncz and SMAC for the convar tester. Maybe there is more.

I will run a test with sourcemod and see if I can do something against this.

The only type of crash I rarely have without running sourcemod is a rate-limite error on the engine, it makes the server hangs for some seconds.

**Comment by blackhawk74** [comment]
Thank you very much! Metamod & Sourcemod compatibility would be paramount in my opinion. I will post my Metamod & Sourcemod versions below to help:

Metamod:Source version 1.10.7-dev (git952)
SourceMod Version: 1.8.0.5946

**Comment by L-EARN** [comment]
Your sourcemod version is outdated.
There has been an update on csgo that is related to the sm patch 5947.

I have tested everything on my side, even with SMAC, all is working good.

However I have someone who also have this issue on a Windows server.

Please update sourcemod.
If it still crashes, send-me an archive of your addons and cfg directories please ( Be sure to strip passwords )

**Comment by blackhawk74** [comment]
The latest version of 1.8 (5947) was only for a possible late-loading Steam Auth fix, in my case not necessary because I was not having this issue. Will update and report back.

As far as sending archive, how can I get this to you privately?

**Comment by L-EARN** [comment]
If you have to send the archive, upload it somewhere with or without a password.
Give me the link to download the archive and the password to open it, if any, to this e-mail address : deseffls6p8yxni@jetable.org ( This address will be available only until 2016-10-23 20:18:00 +0200 CEST )

Thanks.

**Comment by blackhawk74** [comment]
Sent!

**Comment by L-EARN** [comment]
One crash have been fixed.

I have not found more crashes so I dropped a patch here : https://github.com/L-EARN/NoCheatZ-4/releases/tag/v4-beta-r3-patch1

**Comment by blackhawk74** [comment]
Just tried latest patch, still crashing on map end.

**Comment by blackhawk74** [comment]
Just trying to brainstorm, might be a possible plugin conflict, or possibly has to do with number of players? Previously during times of low server population it was not crashing. Still testing on FFA DM server, 9 bots, 2 real players, 15 minute time limit (same time limit as other server that's crashing), no crashes at the moment. Major difference is the Arenas plugin on the other crashing server, and real player count.

**Comment by L-EARN** [comment]
Do you have any minidump I can inspect ?

**Comment by blackhawk74** [comment]
What's the best way for me to get a minidump for you?

**Comment by L-EARN** [comment]
No crash reports ... maybe this is an infinite loop issue.

* Are you running the server on Linux or Windows ?
* Do you have full server access ( Can you edit the start script to start the game server in a debugger ) ?
* In any case, please use the debug version.

Here is the signature of the crash that got fixed earlier : https://crash.limetech.org/stats/67adf4f9c50020d39b3619eab6fbac8321c0029c8d48228440ce3a09a98ec4ddcd0a9f4fb40ef4fb

**Comment by blackhawk74** [comment]
Perhaps, the "crash" isn't characteristic of any other crash I've ever had, at map end the autoreconnect message shows at the top right of the screen, I type retry in console and I connect to the server fine again. Once again, I want to stress that this server has not seen any changes in months, and has not crashed in the same amount of time (outside of the recent CS:GO updates that were patched with updated versions of sourcemod).

Server is Windows, and I unfortunately do not have full access to server, it is on a managed VPS.

Other server has not seen a crash yet, probably because it does not get populated often, it is a new server.

Interestingly enough I just realized I do have minidump files, however they are all failed and empty. Here are some of the file names:
```
(failed)exec_snk1v1_20161016_164541_2_x0030CD20.mdmp
(failed)exec_snk1v1_20161016_164541_1_x0030CD20.mdmp
^^these are after patch 1^^
vv these are before patch 1 vv
(failed)exec_snk1v1_20161015_135429_2_x0031D0F0.mdmp
(failed)exec_snk1v1_20161015_135429_1_x0031D0F0.mdmp
(failed)exec_snk1v1_20161015_133827_2_x0041CFB8.mdmp
(failed)exec_snk1v1_20161015_133827_1_x0041CFB8.mdmp
(failed)exec_snk1v1_20161015_130617_2_x0034C9C0.mdmp
(failed)exec_snk1v1_20161015_130617_1_x0034C9C0.mdmp
```

What does using debug version do? I tried using it on my other server but I did not see any additional logging.

**Comment by L-EARN** [comment]
You get the timeout message but next you are able to connect simply because your gameserver provider has an auto-restart script, this what I think.

The debug version works as the release version with these differences : 
* Symbols are not stripped on linux and .pdb file is shipped with windows, allowing more readable stack traces making crashes more obvious ( When you can have a stack trace )
* The console output has more debugging messages from the plugin ( That you can retrieve in console.log when you enable condebug or partially with rcon sometimes when you enter a command )
* Assertions are included in build, which means sometimes we think a part of code can crash but it should not in normal conditions. Assertions are removed in release mode for performance reasons. If the plugin is supposed to assert, it will crash after in release mode with much less obvious symptoms.
* Build is not optimised at all and performs 2 times slower average.
* Detection messages are also sent to the incrimined player.
* Flashbangs added by the plugin are red so we can compare against the engine normal flashbangs.

The console.log would provide more interesting informations I think.

**Comment by blackhawk74** [comment]
My GSP has an auto restart script and checks for downtime, if the server is still down after 300 seconds it automatically reboots and writes a message in my Event Log, which has not occurred. An instant reboot by a GSP script seems almost unlikely.

Thank you for the helpful information, right now I'm simply waiting for players to connect (usually within an hour from now), and I will report back with logs!

**Comment by L-EARN** [comment]
I'm starting to think it may be a memory issue.

Do you how much of memory is allocated to the server ?

**Comment by blackhawk74** [comment]
I get up to 4gb of memory allocated to each of my server instances, the crashing server rarely sees above 1gb of usage. During usage of nocheatz, according to my graphs the usage has not spiked. http://i.imgur.com/nqNcECc.jpg

My GSP has an option to automatically reboot server if using over 4gb of memory, but it has not once hit that mark (it is logged if this happens).

**Comment by blackhawk74** [comment]
Alright, finally got some logging, hopefully this will be helpful.

[NoCheatZ-17-Oct-2016.txt](https://github.com/L-EARN/NoCheatZ-4/files/534729/NoCheatZ-17-Oct-2016.txt)

[console.txt](https://github.com/L-EARN/NoCheatZ-4/files/534727/console.txt)

Separate thing I noticed, clients are getting kicked for spam connects when they are not spam connecting, plus I have the Spam Connect module disabled.

**Comment by L-EARN** [comment]
Here we are ...

The server is not crashing ; It's just the players who get ip banned after they have done 2 level change.

This might be completly related to the spamconnecttester, that we can't disable ... because I forgot something.

**Comment by blackhawk74** [comment]
If I type "stats" in console, it tells me the server has freshly started (Uptime = 0 and maps = 0), that would generally indicate a server (re)start, no?

There were ~18 users, and in banned_ip.cfg there are only 7 IP's, and 0 in banned_user.cfg

**Comment by L-EARN** [comment]
A new patch is out and should help debugging this issue.

**Comment by blackhawk74** [comment]
Here is !stacktrace.txt after crash, hope this is helpful
[!stacktrace.txt](https://github.com/L-EARN/NoCheatZ-4/files/546776/stacktrace.txt)

**Comment by L-EARN** [comment]
Well, that's pretty fucked up ...

It seems the game engine is throwing a breakpoint.

```
75AEC42C (KERNELBASE)
6D18F1AE tier0.dll (6D180000)
771F63CF (ntdll):
6D18B65E tier0.dll (6D180000)
6BD798CA engine.dll (6BD40000)
6BDFBE90 engine.dll (6BD40000)
6BF17CDD engine.dll (6BD40000)
6BF5C68B engine.dll (6BD40000)
6BF5C779 engine.dll (6BD40000)
6BF5B195 engine.dll (6BD40000)
6BF58A33 engine.dll (6BD40000)
6BF5F8B4 engine.dll (6BD40000)
6C058706 engine.dll ?? (6BD40000)
6D7B3463 metamod.2.csgo.dll (6D7A0000)
5E43C49E ConCommandHookListener::RT_nDispatch(void * const, void *, const SourceSdk::CCommand &)
6BF1AAE4 engine.dll (6BD40000)
6BF19619 engine.dll (6BD40000)
5E42AD3D SourceSdk::InterfacesProxy::Call_ServerExecute(void)
5E323FB1 AutoTVRecord::StopRecord(void)
5E3240DB AutoTVRecord::Unload(void)
5E45B7CA BaseDynamicSystem::SetActive(bool)
5E45BA5D BaseSystem::UnloadAllSystems(void)
5E455507 CNoCheatZPlugin::LevelShutdown(void)
```

**Comment by blackhawk74** [comment]
I disabled AutoTVRecord and so far we've been through 3 maps with 15+ players and no crash.

Interestingly enough, GOTV remains in the server even with the module disabled, and if I type tv_enable 0 (not too familiar with GOTV).

**Comment by L-EARN** [comment]
Maybe you have another plugin that also handles GOTV.

But the game itself is capable of recording games automatically ( This particular non-sense in the plugin makes me think I should disable AutoTVRecord by default on CSGO ).
Problems arrives when you disable the hibernation feature and it might record empty games and blow your disk space.

If you put `tv_autorecord 1` in your `server.cfg`, you will have auto records.
