### ISSUE TITLE
False detection on EyeAngleTester ... Again

### ISSUE THREAD

**Issue by blackhawk74** [L-EARN/NoCheatZ-4#101]
Hello, and sorry for blowing up the Issues section this afternoon!

I had 2 bans from below average to average players today, looking for a second opinion. The bans were triggered so quickly it was hard for me to tell, even with 10% speed in demo review, if they were actually cheating or not.

```
10/15/16 12:14:50 [ Server Tick #38041, SourceTV:NoCheatZ-autorecords/am_lanii-10-15-16_12-10-08.dem : Tick #36110 ] EyeAnglesTester triggered a detection : Italian Spiderman [STEAM_1:1:xx- xx.xx.xx.xx:27005] is using a No recoil.
10/15/16 12:14:50 [ Server Tick #38041, SourceTV:NoCheatZ-autorecords/am_lanii-10-15-16_12-10-08.dem : Tick #36110 ] v4-beta-r3
10/15/16 12:14:50 [ Server Tick #38041, SourceTV:NoCheatZ-autorecords/am_lanii-10-15-16_12-10-08.dem : Tick #36110 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.339870,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 159.989929,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.001097,
:::::::::::: Detections Count : 1d
:::::::: }
:::: }
10/15/16 12:15:00 [ Server Tick #39322, SourceTV:NoCheatZ-autorecords/am_lanii-10-15-16_12-10-08.dem : Tick #37391 ] Player disconnect : Italian Spiderman [STEAM_1:1:xx] -> Reason : Kicked by Console : [NoCheatZ 4] Banned by NoCheatZ 4
```

Demo link: https://drive.google.com/open?id=0B0IJtbqhEr_Jb2UzbG5ZSWxHUFk

My take: I think he gets a fair and square deagle headshot onto his opponent, it is a little strange his movements after while jumping into the water. I attempted to make the glows of enemies a bit clearer, and where he aims and shoots at the box _appears_ slightly above the other player (very far away). Not sure if it could be a coincidence or not.

Second ban:

```
10/15/16 11:48:15 [ Server Tick #82367, SourceTV:NoCheatZ-autorecords/am_skybound-10-15-16_11-37-48.dem : Tick #80308 ] EyeAnglesTester triggered a detection : i_work_at_kfc [STEAM_1:0:xx- xx.xx.xx.xx:27005] is using a No recoil.
10/15/16 11:48:15 [ Server Tick #82367, SourceTV:NoCheatZ-autorecords/am_skybound-10-15-16_11-37-48.dem : Tick #80308 ] v4-beta-r3
10/15/16 11:48:15 [ Server Tick #82367, SourceTV:NoCheatZ-autorecords/am_skybound-10-15-16_11-37-48.dem : Tick #80308 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 25.189293,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : -97.349861,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : -0.000001,
:::::::::::: Detections Count : 1d
:::::::: }
:::: }
10/15/16 11:48:25 [ Server Tick #83648, SourceTV:NoCheatZ-autorecords/am_skybound-10-15-16_11-37-48.dem : Tick #81589 ] Player disconnect : i_work_at_kfc [STEAM_1:0:xx] -> Reason : Kicked by Console : [NoCheatZ 4] Banned by NoCheatZ 4
```

Demo: https://drive.google.com/open?id=0B0IJtbqhEr_JYS1WcmdaYzJxcG8

My thoughts: The round he gets banned, the guy is AFK, returns in a manner where he suddenly does a 180 degree turn facing the ground, starts moving normally, but I feel like his shots flick really fast to the head, but his movement is awful.. It's a 32 tick demo, can't really get too much out of it.

Any sort of help would be super helpful!

**Comment by L-EARN** [comment]
By looking at the demos and this https://github.com/L-EARN/NoCheatZ-4/issues/84#issuecomment-249603940 we can say this false detections ................. :'(

And on the logs a real detection should show a lot more of output, but here they are just a single time detection.

**Comment by blackhawk74** [comment]
Would you like me to upload logs and demos of detections as I get them, or would this not be helpful?

I will be running my 1v1 Arenas server with ncz4 loaded, however without kicking or banning at the moment due to the false positives, I will be manually reviewing each detection.

**Comment by L-EARN** [comment]
It could be interesting to have demos where you have false detection with EyeAngleTester.
A false detection on EyeAngleTester typically just targets the EyeAngleZ and with a very low detection count on the player. But I would like to know in which circonstances the game is modifying this value in order to suppress the false detection the right way, before thinking to remove tests over EyeAngleZ.

So if you have time to do it that would be cool to have demos, the player and the tick where the false detection triggers.

Thanks.

**Comment by blackhawk74** [comment]
Here's a false detection from today. The player seemed to have lagged out/tabbed out of the game, and when detected (~1:20 in the demo) he did snap angles very quickly while still afk. Player has 45 hours on the server, nothing out of the ordinary with him. [Demo File](https://drive.google.com/open?id=0B0IJtbqhEr_JS1RObHFiSFFPb2s)

```
10/25/16 15:10:08 [ Server Tick #9799, SourceTV:am_plain2-10-25-16_13-21-01.dem : Tick #834799 ] EyeAnglesTester triggered a detection : DankLink [STEAM_1:1:xx- xx.xx.xx.xx:27005] is using a Anti-Aim.
10/25/16 15:10:08 [ Server Tick #9799, SourceTV:am_plain2-10-25-16_13-21-01.dem : Tick #834799 ] v4-beta-r3-patch2
10/25/16 15:10:08 [ Server Tick #9799, SourceTV:am_plain2-10-25-16_13-21-01.dem : Tick #834799 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 270.000000,
:::::::::::: Detections Count : 1d
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Detections Count : 0d
:::::::: }
:::: }
```

**Comment by blackhawk74** [comment]
Here's another. Player is definitely not cheating, the detections trip when it appears the client may have alt-tabbed, lagged out, or game crashed. Have a look for yourself (timestamp 11:50): [Demo File](https://drive.google.com/open?id=0B0IJtbqhEr_JNnVFQm9JeWUzLWs)

```
10/25/16 23:19:34 [ Server Tick #89886, SourceTV:am_plain2-10-25-16_19-02-09.dem : Tick #1968914 ] EyeAnglesTester triggered a detection : Elgost Faust [STEAM_1:0:xx - xx.xx.xx.xx:27005] is using a No recoil.
10/25/16 23:19:34 [ Server Tick #89886, SourceTV:am_plain2-10-25-16_19-02-09.dem : Tick #1968914 ] v4-beta-r3-patch2
10/25/16 23:19:34 [ Server Tick #89886, SourceTV:am_plain2-10-25-16_19-02-09.dem : Tick #1968914 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 268.500000,
:::::::::::: Detections Count : 1d
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Detections Count : 0d
:::::::: }
:::: }
10/25/16 23:20:00 [ Server Tick #93290, SourceTV:am_plain2-10-25-16_19-02-09.dem : Tick #1972318 ] EyeAnglesTester triggered a detection : Elgost Faust [STEAM_1:0:xx - xx.xx.xx.xx:27005] is using a No recoil.
10/25/16 23:20:00 [ Server Tick #93290, SourceTV:am_plain2-10-25-16_19-02-09.dem : Tick #1972318 ] v4-beta-r3-patch2
10/25/16 23:20:00 [ Server Tick #93290, SourceTV:am_plain2-10-25-16_19-02-09.dem : Tick #1972318 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 268.500000,
:::::::::::: Detections Count : 2d
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Detections Count : 0d
:::::::: }
:::: }
10/25/16 23:20:07 [ Server Tick #94143, SourceTV:am_plain2-10-25-16_19-02-09.dem : Tick #1973171 ] Player disconnect : Elgost Faust [STEAM_1:0:xx] -> Reason : Your client has failed to reply to a query in time. Please reconnect or restart your game
```

The kick message is from SMAC attempting to query client cvars, and finding it unable to, meaning usually a connection issue or a game crash.

**Comment by blackhawk74** [comment]
Last one from today. I'm gathering that every time someone either loses connection or their game crashes, for some reason they spin once or twice instantly. Super strange. 12:43 timestamp on the demo. [Demo File](https://drive.google.com/open?id=0B0IJtbqhEr_JUDVrWUw4dDJ5NXM)

```
10/25/16 22:49:12 [ Server Tick #98042, SourceTV:am_plain2-10-25-16_19-02-09.dem : Tick #1736559 ] EyeAnglesTester triggered a detection : Snoop Dogg [STEAM_1:1:xx - xx.xx.xx.xx:27005] is using a Anti-Aim.
10/25/16 22:49:12 [ Server Tick #98042, SourceTV:am_plain2-10-25-16_19-02-09.dem : Tick #1736559 ] v4-beta-r3-patch2
10/25/16 22:49:12 [ Server Tick #98042, SourceTV:am_plain2-10-25-16_19-02-09.dem : Tick #1736559 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 270.000000,
:::::::::::: Detections Count : 1d
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Detections Count : 0d
:::::::: }
:::: }
10/25/16 22:49:38 [ Server Tick #101331, SourceTV:am_plain2-10-25-16_19-02-09.dem : Tick #1739848 ] Player connect : K1LL3R [STEAM_1:0:xx]
10/25/16 22:49:38 [ Server Tick #101361, SourceTV:am_plain2-10-25-16_19-02-09.dem : Tick #1739878 ] Player disconnect : Snoop Dogg [STEAM_1:1:xx] -> Reason : Your client has failed to reply to a query in time. Please reconnect or restart your game
```

**Comment by blackhawk74** [comment]
Here's another log of false detections from today. As stated earlier, it appears they happen when a client either crashes, times out, loses connection, or alt-tabs, causing the 265+ degree snap.

**Comment by blackhawk74** [comment]
Don't mean to keep blowing this up, but this detection I found interesting: [multidet.txt](https://github.com/L-EARN/NoCheatZ-4/files/559654/multidet.txt)

Multiple detections, the player was in-game and still able to move around, but he wasn't able to mouse look around.

[Demo file](https://drive.google.com/open?id=0B0IJtbqhEr_JdFVCZVpNdHBoR0U)

**Comment by L-EARN** [comment]
He was not able to look because the plugin drops detected commands.

This is false detection anyway.

**Comment by L-EARN** [comment]
https://github.com/L-EARN/NoCheatZ-4/releases/tag/v4.0.0-r7
