### ISSUE TITLE
make release CXX=g++-4.8

### ISSUE THREAD

**Issue by sam0324sam** [L-EARN/NoCheatZ-4#106]
make: *** No rule to make target 'release'.  Stop.

use debug is the same......what can I do
`Steam>csgoserver@csgoserver-VirtualBox:~/桌面/server/steamcmd$ 
csgoserver@csgoserver-VirtualBox:~/桌面/server/steamcmd$ git clone git://github.com/L-EARN/NoCheatZ-4.git
Cloning into 'NoCheatZ-4'...
remote: Counting objects: 3041, done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 3041 (delta 69), reused 0 (delta 0), pack-reused 2939
Receiving objects: 100% (3041/3041), 691.37 KiB | 104.00 KiB/s, done.
Resolving deltas: 100% (2419/2419), done.
Checking connectivity... done.
csgoserver@csgoserver-VirtualBox:~/桌面/server/steamcmd$ cd NoCheatZ-4
csgoserver@csgoserver-VirtualBox:~/桌面/server/steamcmd/NoCheatZ-4$ git submodule update --init
Submodule 'sourcesdk' (https://github.com/L-EARN/SourceSdk-ServerPlugin.git) registered for path 'server-plugin/SourceSdk'
Cloning into 'server-plugin/SourceSdk'...
remote: Counting objects: 1091, done.
remote: Total 1091 (delta 0), reused 0 (delta 0), pack-reused 1091
Receiving objects: 100% (1091/1091), 4.13 MiB | 1.07 MiB/s, done.
Resolving deltas: 100% (473/473), done.
Checking connectivity... done.
Submodule path 'server-plugin/SourceSdk': checked out '34d303f8d0d22c0cd76bb455181426923071c6b3'
csgoserver@csgoserver-VirtualBox:~/桌面/server/steamcmd/NoCheatZ-4$ su
密碼： 
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server/steamcmd/NoCheatZ-4# dpkg --add-architecture i386
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server/steamcmd/NoCheatZ-4# apt-get update
已有:1 http://tw.archive.ubuntu.com/ubuntu xenial InRelease
已有:2 http://tw.archive.ubuntu.com/ubuntu xenial-updates InRelease            
已有:3 http://tw.archive.ubuntu.com/ubuntu xenial-backports InRelease          
下載:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]   
取得 94.5 kB 用了 1秒 (66.3 kB/s)                     
正在讀取套件清單... 完成
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server/steamcmd/NoCheatZ-4# apt-get install git g++ g++-multilib build-essential ia32-libs lib32gcc1 libc6-i386 libc6-dev-i386 autotools-dev autoconf libtool gdb screen
正在讀取套件清單... 完成
正在重建相依關係          
正在讀取狀態資料... 完成
無法取得套件 ia32-libs，但它卻被其它的套件引用了。
這意味著這個套件可能已經消失了、被廢棄了，或是只能由其他的來源取得
然而，下列的套件取代了它：
  lib32ncurses5 lib32z1

E: ia32-libs 套件無可安裝版本
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server/steamcmd/NoCheatZ-4# apt-get install git g++ g++-multilib build-essential ia32-libs lib32gcc1 libc6-i386 libc6-dev-i386 autotools-dev autoconf libtool gdb screen
正在讀取套件清單... 完成
正在重建相依關係          
正在讀取狀態資料... 完成
無法取得套件 ia32-libs，但它卻被其它的套件引用了。
這意味著這個套件可能已經消失了、被廢棄了，或是只能由其他的來源取得
然而，下列的套件取代了它：
  lib32ncurses5 lib32z1

E: ia32-libs 套件無可安裝版本
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server/steamcmd/NoCheatZ-4# apt-get install git g++ g++-multilib build-essential lib32z1  lib32gcc1 libc6-i386 libc6-dev-i386 autotools-dev autoconf libtool gdb screen
正在讀取套件清單... 完成
正在重建相依關係          
正在讀取狀態資料... 完成
build-essential is already the newest version (12.1ubuntu2).
build-essential 被設定為手動安裝。
g++ is already the newest version (4:5.3.1-1ubuntu1).
g++ 被設定為手動安裝。
git is already the newest version (1:2.7.4-0ubuntu1).
lib32gcc1 is already the newest version (1:6.0.1-0ubuntu1).
libc6-dev-i386 is already the newest version (2.23-0ubuntu3).
libc6-dev-i386 被設定為手動安裝。
libc6-i386 is already the newest version (2.23-0ubuntu3).
libc6-i386 被設定為手動安裝。
gdb is already the newest version (7.11.1-0ubuntu1~16.04).
gdb 被設定為手動安裝。
建議套件：
  autoconf-archive gnu-standards autoconf-doc lib32stdc++6-5-dbg
  libx32stdc++6-5-dbg libtool-doc gfortran | fortran95-compiler gcj-jdk
  iselect | screenie | byobu ncurses-term
下列【新】套件將會被安裝：
  autoconf automake autotools-dev g++-5-multilib g++-multilib
  lib32stdc++-5-dev lib32z1 libltdl-dev libsigsegv2 libtool libx32stdc++-5-dev
  m4 screen
升級 0 個，新安裝 13 個，移除 0 個，有 143 個未被升級。
需要下載 3,294 kB 的套件檔。
此操作完成之後，會多佔用 26.2 MB 的磁碟空間。
下載:1 http://tw.archive.ubuntu.com/ubuntu xenial/main amd64 libsigsegv2 amd64 2.10-4 [14.1 kB]
下載:2 http://tw.archive.ubuntu.com/ubuntu xenial/main amd64 m4 amd64 1.4.17-5 [195 kB]
下載:3 http://tw.archive.ubuntu.com/ubuntu xenial/main amd64 autoconf all 2.69-9 [321 kB]
下載:4 http://tw.archive.ubuntu.com/ubuntu xenial/main amd64 autotools-dev all 20150820.1 [39.8 kB]
下載:5 http://tw.archive.ubuntu.com/ubuntu xenial/main amd64 automake all 1:1.15-4ubuntu1 [510 kB]
下載:6 http://tw.archive.ubuntu.com/ubuntu xenial-updates/main amd64 lib32stdc++-5-dev amd64 5.4.0-6ubuntu1~16.04.2 [637 kB]
下載:7 http://tw.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libx32stdc++-5-dev amd64 5.4.0-6ubuntu1~16.04.2 [610 kB]
下載:8 http://tw.archive.ubuntu.com/ubuntu xenial-updates/main amd64 g++-5-multilib amd64 5.4.0-6ubuntu1~16.04.2 [986 B]
下載:9 http://tw.archive.ubuntu.com/ubuntu xenial/main amd64 g++-multilib amd64 4:5.3.1-1ubuntu1 [940 B]
下載:10 http://tw.archive.ubuntu.com/ubuntu xenial/main amd64 lib32z1 amd64 1:1.2.8.dfsg-2ubuntu4 [52.2 kB]
下載:11 http://tw.archive.ubuntu.com/ubuntu xenial/main amd64 libltdl-dev amd64 2.4.6-0.1 [162 kB]
下載:12 http://tw.archive.ubuntu.com/ubuntu xenial/main amd64 libtool all 2.4.6-0.1 [193 kB]
下載:13 http://tw.archive.ubuntu.com/ubuntu xenial/main amd64 screen amd64 4.3.1-2build1 [560 kB]
取得 3,294 kB 用了 0秒 (4,551 kB/s)
選取了原先未選的套件 libsigsegv2:amd64。
（讀取資料庫 ... 目前共安裝了 214694 個檔案和目錄。）
準備解開 .../libsigsegv2_2.10-4_amd64.deb ...
解開 libsigsegv2:amd64 (2.10-4) 中...
選取了原先未選的套件 m4。
準備解開 .../archives/m4_1.4.17-5_amd64.deb ...
解開 m4 (1.4.17-5) 中...
選取了原先未選的套件 autoconf。
準備解開 .../autoconf_2.69-9_all.deb ...
解開 autoconf (2.69-9) 中...
選取了原先未選的套件 autotools-dev。
準備解開 .../autotools-dev_20150820.1_all.deb ...
解開 autotools-dev (20150820.1) 中...
選取了原先未選的套件 automake。
準備解開 .../automake_1%3a1.15-4ubuntu1_all.deb ...
解開 automake (1:1.15-4ubuntu1) 中...
選取了原先未選的套件 lib32stdc++-5-dev。
準備解開 .../lib32stdc++-5-dev_5.4.0-6ubuntu1~16.04.2_amd64.deb ...
解開 lib32stdc++-5-dev (5.4.0-6ubuntu1~16.04.2) 中...
選取了原先未選的套件 libx32stdc++-5-dev。
準備解開 .../libx32stdc++-5-dev_5.4.0-6ubuntu1~16.04.2_amd64.deb ...
解開 libx32stdc++-5-dev (5.4.0-6ubuntu1~16.04.2) 中...
選取了原先未選的套件 g++-5-multilib。
準備解開 .../g++-5-multilib_5.4.0-6ubuntu1~16.04.2_amd64.deb ...
解開 g++-5-multilib (5.4.0-6ubuntu1~16.04.2) 中...
選取了原先未選的套件 g++-multilib。
準備解開 .../g++-multilib_4%3a5.3.1-1ubuntu1_amd64.deb ...
解開 g++-multilib (4:5.3.1-1ubuntu1) 中...
選取了原先未選的套件 lib32z1。
準備解開 .../lib32z1_1%3a1.2.8.dfsg-2ubuntu4_amd64.deb ...
解開 lib32z1 (1:1.2.8.dfsg-2ubuntu4) 中...
選取了原先未選的套件 libltdl-dev:amd64。
準備解開 .../libltdl-dev_2.4.6-0.1_amd64.deb ...
解開 libltdl-dev:amd64 (2.4.6-0.1) 中...
選取了原先未選的套件 libtool。
準備解開 .../libtool_2.4.6-0.1_all.deb ...
解開 libtool (2.4.6-0.1) 中...
選取了原先未選的套件 screen。
準備解開 .../screen_4.3.1-2build1_amd64.deb ...
解開 screen (4.3.1-2build1) 中...
Processing triggers for install-info (6.1.0.dfsg.1-5) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for doc-base (0.10.7) ...
正在處理 1 added doc-base file...
Processing triggers for systemd (229-4ubuntu10) ...
Processing triggers for ureadahead (0.100.0-19) ...
設定 libsigsegv2:amd64 (2.10-4) ...
設定 m4 (1.4.17-5) ...
設定 autoconf (2.69-9) ...
設定 autotools-dev (20150820.1) ...
設定 automake (1:1.15-4ubuntu1) ...
update-alternatives: using /usr/bin/automake-1.15 to provide /usr/bin/automake (automake) in auto mode
設定 lib32stdc++-5-dev (5.4.0-6ubuntu1~16.04.2) ...
設定 libx32stdc++-5-dev (5.4.0-6ubuntu1~16.04.2) ...
設定 g++-5-multilib (5.4.0-6ubuntu1~16.04.2) ...
設定 g++-multilib (4:5.3.1-1ubuntu1) ...
設定 lib32z1 (1:1.2.8.dfsg-2ubuntu4) ...
設定 libltdl-dev:amd64 (2.4.6-0.1) ...
設定 libtool (2.4.6-0.1) ...
設定 screen (4.3.1-2build1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for systemd (229-4ubuntu10) ...
Processing triggers for ureadahead (0.100.0-19) ...
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server/steamcmd/NoCheatZ-4# apt-get install g++-4.8 g++-4.8-multilib
正在讀取套件清單... 完成
正在重建相依關係          
正在讀取狀態資料... 完成
g++-4.8 is already the newest version (4.8.5-4ubuntu2).
g++-4.8-multilib is already the newest version (4.8.5-4ubuntu2).
升級 0 個，新安裝 0 個，移除 0 個，有 143 個未被升級。
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server/steamcmd/NoCheatZ-4# cd ..
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server/steamcmd# cd ..
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server# cd /home/csgoserver/桌 面/server/serverfiles/csgo/addons/sourcemod
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server/serverfiles/csgo/addons/
sourcemod# cd ..
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server/serverfiles/csgo/addons#
 cd 
metamod/     metamod.vdf  sourcemod/   
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server/serverfiles/csgo/addons#
 cd sourcemod/
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server/serverfiles/csgo/addons/
sourcemod# cd 
bin/          examples/     GPLv2.txt     logs/         translations/
configs/      extensions/   GPLv3.txt     plugins/      
data/         gamedata/     LICENSE.txt   scripting/    
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server/serverfiles/csgo/addons/
sourcemod# cd plugins/
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server/serverfiles/csgo/addons/
sourcemod/plugins# make debug CXX=g++-4.8
make: *** No rule to make target 'debug'.  Stop.
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server/serverfiles/csgo/addons/
sourcemod/plugins# make release CXX=g++-4.8
make: *** No rule to make target 'release'.  Stop.
root@csgoserver-VirtualBox:/home/csgoserver/桌面/server/serverfiles/csgo/addons/
sourcemod/plugins# 
`

**Comment by L-EARN** [comment]
Hi,

Note this is not a sourcemod or metamod plugin.

```
cd /桌面/server/steamcmd/NoCheatZ-4/server-plugin
make release CXX=g++-4.8
cp -Rv /桌面/server/steamcmd/NoCheatZ-4/Builds/Release/* /home/csgoserver/桌面/server/serverfiles/csgo
```

**Comment by sam0324sam** [comment]
Oh it's NoCheatZ-4/server-plugin folder not sourcemod/plugins folder!?
