### ISSUE TITLE
how can I disable AutoTVRecord

### ISSUE THREAD

**Issue by sam0324sam** [L-EARN/NoCheatZ-4#107]
I type "ncz AutoTVRecord disable" in console but it is continue record.
I have anyother record plugin and I don't want to record the same record.
please help

**Comment by L-EARN** [comment]
Edit the config.ini file, line 25 : 

`disable_systems=ValidationTester;RadarHackBlocker;BadUserCmdBlocker;AutoTVRecord`

Next restart the server.

**Comment by sam0324sam** [comment]
thanks!
