### ISSUE TITLE
crash on debian8 csgo (meta / sm disabled)

### ISSUE THREAD

**Issue by gonkong** [L-EARN/NoCheatZ-4#108]
Server does not start

[NoCheatZ v4-beta-r3-patch1-debug] 1.049233 DEBUG : CNoCheatZPlugin::ServerActivate (pEdictList:0xed6ff020, edictCount:410, clientMax:64)
srcds_linux: ../server-plugin/Code/Misc/EntityProps.h:250: T* EntityProps::GetPropValue(SourceSdk::edict_t*, bool) [with T = bool; UsedProps prop_id = (UsedProps)4u]: Assertion `offset > 0' failed.
PreMinidumpCallback: updating dump comment
crash_20161021022849_1.dmp[11186]: Uploading dump (out-of-process)
/tmp/dumps/crash_20161021022849_1.dmp
crash_20161021022849_1.dmp[11186]: Finished uploading minidump (out-of-process): success = no
crash_20161021022849_1.dmp[11186]: error: libcurl.so: cannot open shared object file: No such file or directory
crash_20161021022849_1.dmp[11186]: file ''/tmp/dumps/crash_20161021022849_1.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
Aborted (core dumped)
BFD: Предупреждение: /home/deb/steam_pipe/csg3/core усечён: ожидался размер ядра файла >= 334155776, найдено: 1019904.
Cannot access memory at address 0xf77e091c
Cannot access memory at address 0xf77e0918
Python Exception <class 'gdb.MemoryError'> Cannot access memory at address 0xffb54b74:
debug.cmds:1: Error in sourced command file:
Cannot access memory at address 0xffb54b74
Server Quit

**Comment by L-EARN** [comment]
Hi,

Please don't enable RadarHackBlocker on CSGO. It's not working for this game.
