### ISSUE TITLE
Disconnect: You are spam connecting. Please wait 20 minutes

### ISSUE THREAD

**Issue by gonkong** [L-EARN/NoCheatZ-4#109]
how to disable?
this mass problem

Can't change replicated ConVar nextlevel from console of client, only server operator can change its value
Disconnect: You are spam connecting. Please wait 20 minutes..
Disconnect: You are spam connecting. Please wait 20 minutes..

disable_systems=ValidationTester;BadUserCmdBlocker;AutoTVRecord;RadarHackBlocker;SpamConnectTester

// Testers

ncz ConCommandTester disable
ncz ConVarTester disable
ncz EyeAnglesTester enable
ncz JumpTester disable
ncz AutoAttackTester enable
ncz SpamChangeNameTester disable
ncz SpamConnectTester disable
ncz SpeedTester disable
ncz ValidationTester disable

// Blockers

ncz AntiFlashbangBlocker enable
ncz RadarHackBlocker disable
ncz AntiSmokeBlocker enable
ncz BadUserCmdBlocker disable
ncz WallhackBlocker enable
ncz BhopBlocker disable

// Misc

ncz BanRequest CanKick Yes
ncz BanRequest CanBan Yes

10/22/16 00:45:26 [ Server Tick #65, SourceTV:NoCheatZ-autorecords/de_dust2_2x2-10-21-16_20-50-25.dem : Tick #900905 ] PLAYING ON A NEW MAP : de_dust2

10/22/16 00:45:27 [ Server Tick #71, SourceTV:NoCheatZ-autorecords/de_dust2_2x2-10-21-16_20-50-25.dem : Tick #900911 ] CNoCheatZPlugin::ClientConnect : Rejected 46.187.33.76:27005 with reason You are spam connecting. Please wait 20 minutes.
10/22/16 00:45:27 [ Server Tick #71, SourceTV:NoCheatZ-autorecords/de_dust2_2x2-10-21-16_20-50-25.dem : Tick #900911 ] Player disconnect : Qewbite | kickback.com  -> Reason : You are spam connecting. Please wait 20 minutes.
10/22/16 00:45:27 [ Server Tick #71, SourceTV:NoCheatZ-autorecords/de_dust2_2x2-10-21-16_20-50-25.dem : Tick #900911 ] CNoCheatZPlugin::ClientConnect : Rejected ------ with reason You are spam connecting. Please wait 20 minutes.
10/22/16 00:45:27 [ Server Tick #71, SourceTV:NoCheatZ-autorecords/de_dust2_2x2-10-21-16_20-50-25.dem : Tick #900911 ] Player disconnect : ---- [] -> Reason : You are spam connecting. Please wait 20 minutes.
10/22/16 00:45:27 [ Server Tick #71, SourceTV:NoCheatZ-autorecords/de_dust2_2x2-10-21-16_20-50-25.dem : Tick #900911 ] CNoCheatZPlugin::ClientConnect : Rejected 31.132.98.128:27005 with reason You are spam connecting. Please wait 20 minutes.
10/22/16 00:45:27 [ Server Tick #71, SourceTV:NoCheatZ-autorecords/de_dust2_2x2-10-21-16_20-50-25.dem : Tick #900911 ] Player disconnect : Peredoxe!? -> Reason : You are spam connecting. Please wait 20 minutes.
10/22/16 00:45:28 [ Server Tick #123, SourceTV:NoCheatZ-autorecords/de_dust2_2x2-10-21-16_20-50-25.dem : Tick #900963 ] CNoCheatZPlugin::ClientConnect : Rejected 176.99.228.3:38365 with reason You are spam connecting. Please wait 20 minutes.
10/22/16 00:45:28 [ Server Tick #123, SourceTV:NoCheatZ-autorecords/de_dust2_2x2-10-21-16_20-50-25.dem : Tick #900963 ] Player disconnect : bepatient_BorNeo  -> Reason : You are spam connecting. Please wait 20 minutes.

**Comment by L-EARN** [comment]
It's currently being fixed.
