### ISSUE TITLE
unban

### ISSUE THREAD

**Issue by sam0324sam** [L-EARN/NoCheatZ-4#110]
can I unban myfriend?
I let him test my server....but he get ncz ban....

**Comment by L-EARN** [comment]
Hi,

Use the `listid` command to retrieve the ban number of the Steam ID of your friend.
Then use the `removeid` command to remove the entry given the number.
After that do the same with `listip` and `removeip`.

When you finished to remove bans, use `writeid` and `writeip` commands.

> **listid**
> ID filter list: 1 entry
> 1 STEAM_1:0:1 : permanent
> **removeid 1**
> removeid:  filter removed for 1, ID STEAM_1:0:1
> **listip**
> IP filter list: 1 entry
> 1 192.168.  1.  1 : permanent
> **removeip 1**
> removeip:  filter removed for 1, IP 192.168.  1.  1
> **writeid**
> **writeip**
