### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by gonkong** [L-EARN/NoCheatZ-4#112]
Add filter to chat.
Some cheats says spam in chat. If we write a text in the config file, you can ban these players without finding cheats.

**Comment by L-EARN** [comment]
Hi,

This is something I already though.

But there is also clean players who are trolling by sending those kind of messages too so I will sadly not implement this test.

**Comment by gonkong** [comment]
many projects are taking a trolling as advertising cheats, and give ban

**Comment by blackhawk74** [comment]
There are sourcemod plugins available for use in this circumstance.
