### ISSUE TITLE
CS:GO - False Detections

### ISSUE THREAD

**Issue by blackhawk74** [L-EARN/NoCheatZ-4#113]
Just had 5 separate players banned within an hour of each other, would appreciate any help to determine if whether or not they were cheating. A few of them has been on my servers quite a bit, and have never picked up a single detection. Unfortunately do not have a demo file, as we discussed earlier I am testing for crashes without AutoTVRecord enabled.

A couple things I noticed prior to logs:
- Nocheatz is referencing a demo file from 3 hours prior, with AutoTVRecord off
- Sourcebans support now fully working (woohoo!), however it would be nice if the userid's weren't written to banned_user.cfg if sent to sourcebans properly. Generally if an unban needs to come through sourcebans, banned_user.cfg isn't looked at, and would be another step in the process.
- Small thing - the ban message by default is "Banned by NoCheatZ 4" - can this be adjusted to include by what module (type of detection)? Such as: "Banned by NoCheatZ 4 - Aimbot Detected" or similar. I can create a separate Issue on this topic if you'd like

Logs attached
[NoCheatZ-24-Oct-2016.txt](https://github.com/L-EARN/NoCheatZ-4/files/549340/NoCheatZ-24-Oct-2016.txt)

Of the lot, I can only say with confidence that Walls.EXE was definitively hacking

**Comment by L-EARN** [comment]
Hi,

Both seems ok, Pop got more evidence than A3.

I can say it's REALLY safe to assume that Pop was using something not human.

Also be aware a faulting mouse might be detected the same, and using mwheel on the fire button will also be detected.

And in this particular report I think A3 had a faulting mouse. You might ask him to check that.

**Comment by L-EARN** [comment]
Here is the shot-graph of Pop.
X axis represents the time elapsed in seconds.
Y axis represents the sustain time of the shot button, in seconds.
![pop](https://cloud.githubusercontent.com/assets/13771307/19669825/bab1f8ec-9a62-11e6-8ec6-7e80103c097b.png)

As you can see almost all detections (80) are split into 2 regions.

Here is the shot-graph of A3 : 
![a3](https://cloud.githubusercontent.com/assets/13771307/19669826/bab5519a-9a62-11e6-9a5f-82ccb5e4f4bf.jpg)
Something went wrong but it is unsure whether it is a cheat or not.

**Comment by blackhawk74** [comment]
Apologies, didn't have the log file formatted well, I included the 3 other players. Two of which I am actually surprised got picked up for anything, one has 15 hours on the server and has never looked sketchy, and has a decently valued CS:GO inventory. Here are the logs for the other players: 
[24log.txt](https://github.com/L-EARN/NoCheatZ-4/files/549792/24log.txt)

The visuals are super helpful by the way, is it a simple process to create or no? I hate to keep asking more of you! You're doing an excellent job, and putting up with me has got to be obnoxious, I'm sure. :)

**Comment by L-EARN** [comment]
WoLf -> is related to #101 
Backs -> 100% sure it's good detection
mrc1104 -> Same graph as A3 ?

For the visuals I just put values in Open Office but really boring to do. Before that I already though to make the plugin draw a .bmp file for visuals, and this might be implemented next and also for the eye angle tester and maybe fo the jumptester.
