### ISSUE TITLE
JumpTester - Overly Aggressive

### ISSUE THREAD

**Issue by blackhawk74** [L-EARN/NoCheatZ-4#120]
Currently, the jumptester is extremely aggressive. Many players bind +jump to scroll wheel, which is extremely common practice (normal players, players who are into bhop, many pro players, etc). Right now, after a single jump, using scrollwheel will get the player kicked before even hitting the ground.

As we discussed in #77, the module works, however it is not useful for banning actual cheaters. My recommendations for this module to be effective:
- Kicks/Bans for repeated perfect/near perfect consistent jump ratio/time between jumps, see [Macrodox](https://forums.alliedmods.net/showthread.php?p=1678026) as an example)
- Kicks/bans based off of consistently hitting perfect bhops (see autotrigger module from [smac](http://smac.sx/))

I think many server owners, such as myself would be more interested in banning cheaters who are using actual injected cheats, than players who are using scroll wheel or even autohotkey. Those should be differentiated and customizable.

This is what a current JumpTester detection only using +jump bound to scroll wheel looks like:

```
10/25/16 02:04:57 [ Server Tick #2733, SourceTV:am_plain2-10-25-16_01-51-15.dem : Tick #105151 ] JumpTester triggered a detection : sneaK [STEAM_1:0:xx - xx.xx.xx.xx:27005] is using a BunnyHop Script.
10/25/16 02:04:57 [ Server Tick #2733, SourceTV:am_plain2-10-25-16_01-51-15.dem : Tick #105151 ] v4-beta-r3-patch2
10/25/16 02:04:57 [ Server Tick #2733, SourceTV:am_plain2-10-25-16_01-51-15.dem : Tick #105151 ] :::: BunnyHopInfoT {
:::::::: OnGroundHolderT {
:::::::::::: On Ground At (Tick #) : 0,
:::::::::::: Leave Ground At (Tick #) : 2719,
:::::::::::: Jump Count : 1
:::::::: },
:::::::: JumpCmdHolderT {
:::::::::::: Last Jump Command : Button Down s,
:::::::::::: Jump Button Down At (Tick #) : 2733,
:::::::::::: Jump Button Up At (Tick #) : 2730,
:::::::::::: Jump Commands Done While Flying : 3
:::::::: },
:::::::: Total Bunny Hop Count : 0,
:::::::: Good Bunny Hop Count : 0,
:::::::: Perfect Bunny Hop Ratio : 0 %,
:::::::: Perfect Bunny Hop Count : 0
:::: }
10/25/16 02:04:57 [ Server Tick #2733, SourceTV:am_plain2-10-25-16_01-51-15.dem : Tick #105151 ] Kicked sneaK [STEAM_1:0:xx - xx.xx.xx.xx:27005] with reason : You have to turn off your BunnyHop Script to play on this server.

10/25/16 02:04:57 [ Server Tick #2733, SourceTV:am_plain2-10-25-16_01-51-15.dem : Tick #105151 ] Player disconnect : sneaK [STEAM_1:0:xx] -> Reason : Kicked by Console : [NoCheatZ 4] You have to turn off your BunnyHop Script to play on this server.
```

**Comment by Sandman007** [comment]
Is this getting fixed soon? I just had to disable this on my end as well for the exact same issue.

**Comment by L-EARN** [comment]
Hi,

You have now the possibility to make JumpTester ban, kick or only log detections.
This is not a direct fix for this issue, but you were a lot complaining about this particular system.

I will calibrate this system soon, issue still open.

**Comment by L-EARN** [comment]
https://github.com/L-EARN/NoCheatZ-4/releases/tag/v4.0.0-r7
