### ISSUE TITLE
Feature Request: Ban Message

### ISSUE THREAD

**Issue by blackhawk74** [L-EARN/NoCheatZ-4#121]
Right now the default ban message is "Banned by NoCheatZ 4"

Would this be possible to be changed to something more specific like "Banned by NoCheatZ 4 - Anti-Aim Detected" or similar?

**Comment by L-EARN** [comment]
Related #117

**Comment by L-EARN** [comment]
Coming soon. ref https://github.com/L-EARN/NoCheatZ-4/pull/147/commits/59a4ff2552de290b684e3f1dffdfa76a5c884f74
