### ISSUE TITLE
Feature Request: Ban Writing Option

### ISSUE THREAD

**Issue by blackhawk74** [L-EARN/NoCheatZ-4#122]
In the current state, if sm_ban is available it is used, and bans are written to banned_user.cfg. However, for those of us with 3rd party ban/administration systems (such as SourceBans), it would be helpful to have an option to disable writing to banned_user.cfg/banned_ip.cfg, as SourceBans already takes care of bans. This would eliminate an extra step of manually removing IP's and ID's.

**Comment by L-EARN** [comment]
Related #117
