### ISSUE TITLE
EyeAnglesTester triggered a detection : *** is using a Anti-Aim.

### ISSUE THREAD

**Issue by gonkong** [L-EARN/NoCheatZ-4#123]
Player said that he received a ban.  In the logs it is true. I looked at the demo, there was no warning on the screen/chat. The player said goodbye and walked out from the server, did not kick. At the time of disconnection, according to the logs, the player will get banned.

This is normal behavior?
How to understand this true or false detection?

10/28/16 12:39:12 [ Server Tick #42222, SourceTV:de_dust2x2_reloaded-10-28-16_08-23-50.dem : Tick #979337 ] EyeAnglesTester triggered a detection : *** is using a Anti-Aim.
10/28/16 12:39:12 [ Server Tick #42222, SourceTV:de_dust2x2_reloaded-10-28-16_08-23-50.dem : Tick #979337 ] v4-beta-r3-patch2
10/28/16 12:39:12 [ Server Tick #42222, SourceTV:de_dust2x2_reloaded-10-28-16_08-23-50.dem : Tick #979337 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 186.000000,
:::::::::::: Detections Count : 1d
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Detections Count : 0d
:::::::: }
:::: }
10/28/16 12:39:16 [ Server Tick #42512, SourceTV:de_dust2x2_reloaded-10-28-16_08-23-50.dem : Tick #979627 ] EyeAnglesTester triggered a detection : *** is using a Anti-Aim.
10/28/16 12:39:16 [ Server Tick #42512, SourceTV:de_dust2x2_reloaded-10-28-16_08-23-50.dem : Tick #979627 ] v4-beta-r3-patch2
10/28/16 12:39:16 [ Server Tick #42512, SourceTV:de_dust2x2_reloaded-10-28-16_08-23-50.dem : Tick #979627 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 186.000000,
:::::::::::: Detections Count : 146d
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Detections Count : 0d
:::::::: }
:::: }
10/28/16 12:39:21 [ Server Tick #42802, SourceTV:de_dust2x2_reloaded-10-28-16_08-23-50.dem : Tick #979917 ] EyeAnglesTester triggered a detection : *** is using a Anti-Aim.
10/28/16 12:39:21 [ Server Tick #42802, SourceTV:de_dust2x2_reloaded-10-28-16_08-23-50.dem : Tick #979917 ] v4-beta-r3-patch2
10/28/16 12:39:21 [ Server Tick #42802, SourceTV:de_dust2x2_reloaded-10-28-16_08-23-50.dem : Tick #979917 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 186.000000,
:::::::::::: Detections Count : 291d
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Detections Count : 0d
:::::::: }
:::: }
10/28/16 12:39:22 [ Server Tick #42864, SourceTV:de_dust2x2_reloaded-10-28-16_08-23-50.dem : Tick #979979 ] Player disconnect :*** -> Reason : Kicked by Console : [NoCheatZ 4] Banned by NoCheatZ 4

disable_systems=ValidationTester;RadarHackBlocker;BadUserCmdBlocker;AutoTVRecord

// Testers

ncz ConCommandTester disable
ncz ConVarTester disable
ncz EyeAnglesTester enable
ncz JumpTester disable
ncz AutoAttackTester enable
ncz SpamChangeNameTester disable
ncz SpamConnectTester disable
ncz SpeedTester enable
ncz ValidationTester disable

// Blockers

ncz AntiFlashbangBlocker enable
ncz RadarHackBlocker disable
ncz AntiSmokeBlocker enable
ncz BadUserCmdBlocker disable
ncz WallhackBlocker enable
ncz BhopBlocker disable

// Misc

ncz BanRequest CanKick Yes
ncz BanRequest CanBan Yes

**Comment by L-EARN** [comment]
This is related to #101 
You might consider this sytem failing entirely and disable it.
