### ISSUE TITLE
The server is not responding. Error in `./srcds_linux': corrupted double-linked list: 

### ISSUE THREAD

**Issue by gonkong** [L-EARN/NoCheatZ-4#126]
DEB8
when rebooting the server, using the plugin

L 10/28/2016 - 21:29:02: Error log file session closed.
**\* Error in `./srcds_linux': corrupted double-linked list: 0x0c0012b0 ***
Opening /home/***/steam_pipe/csg2/csgo/addons/NoCheatZ/!stacktrace.txt 

The server is not responding

stacktrace.txt  -not found

**Comment by L-EARN** [comment]
This error only arise when you reboot but not in normal conditions ?

This kind of error happens often when we link C++99 and c++11 programs on linux when using standard library features. I must check if the protobuf is not compiled using c++11 ...

**Comment by L-EARN** [comment]
Hi, please test with r4.
https://github.com/L-EARN/NoCheatZ-4/releases/tag/v4-beta-r4
