### ISSUE TITLE
How to Install on Linux Gameserver without SSH connection?

### ISSUE THREAD

**Issue by Bl4CkGuuN** [L-EARN/NoCheatZ-4#128]

**Comment by morpig** [comment]
you should use SSH in order to install steamcmd, csgo srcds, and things. If you don't want to use SSH, then use a gaming provider with a control panel on it.

**Comment by Bl4CkGuuN** [comment]
What do you mean with control panel?`

I mean I can do everything with this Gameserver expect SSH things

**Comment by L-EARN** [comment]
This plugin is not available using the control panel of any provider, because it is not known enough.

The only way to install it is to effectively have access to files and upload it on the server, using FTP for instance.
