### ISSUE TITLE
[Question] Bot recognize

### ISSUE THREAD

**Issue by Nerus87** [L-EARN/NoCheatZ-4#129]
Hi, 
is this plugin recognize bots automatically ?

If not,
please add feature to improve performance.

Regards,
Nerus

**Comment by L-EARN** [comment]
Hi,

The plugin recognize bots, alive players, dead players, spectators, TVs, server ...
I'm not sure about hostages, it's not tested.

All these things are stored in a static array with a personnalized iterator.
Peformance issue is not related to this.

I close this issue. If you remember more about performance issues, please explain.

**Comment by Nerus87** [comment]
I mean "is this plugin will not checks bots" - in this way.

**Comment by L-EARN** [comment]
Are you talking about AI (game bots) or cheats (aimbots) ?

**Comment by Nerus87** [comment]
Sorry, gamebots - if plugin check players are not a humans.

**Comment by L-EARN** [comment]
Yes it does.
