### ISSUE TITLE
[CSS] Crash server on join team before round start

### ISSUE THREAD

**Issue by Nerus87** [L-EARN/NoCheatZ-4#130]
I've join to team and server crush, 

I have last sourcemod 1.8 and my own plugin **spawn on round start event** after "**jointeam**" command.

> 11/12/16 15:40:39 [ Server Tick #300] PLAYING ON A NEW MAP : de_dust2
> 11/12/16 15:41:05 [ Server Tick #8026] Player connect : Nerus (removed)
> 11/12/16 15:41:06 [ Server Tick #8347] TV not detected. Reloading the map ...
> 11/12/16 15:41:07 [ Server Tick #300] PLAYING ON A NEW MAP : de_dust2
> 11/12/16 15:41:12 [ Server Tick #1812] Starting to record the game in de_dust2-11-12-16_15-41-12.dem
> 11/12/16 15:49:32 [ Server Tick #151845, SourceTV:de_dust2-11-12-16_15-41-12.dem : Tick #150034 ] Player disconnect : Nerus  (removed) -> Reason : Kicked from server
> 11/12/16 15:49:32 [ Server Tick #151845] TV record ended in de_dust2-11-12-16_15-41-12.dem with 150034 ticks (500.113345 seconds)
> 11/12/16 15:52:01 [ Server Tick #196424] Player connect : Nerus (removed)
> 11/12/16 15:52:22 [ Server Tick #300] PLAYING ON A NEW MAP : de_dust2

**Comment by tooshkan4uk** [comment]
tv_enable 1 in server.cfg

**Comment by L-EARN** [comment]
Hi,

If you remember, can you tell me if enabling the TV solved the problem or not ?

**Comment by Nerus87** [comment]
Basically i don't remember if was enabled or not but I have news:

It is a clean server:

> [NoCheatZ v4-beta-r3-patch2-debug] 71.932277 DEBUG : CNoCheatZPlugin::NetworkIDValidated (pszUserName:Iwi#, pszNetworkID:[U:1:362948679])
> [NoCheatZ v4-beta-r3-patch2-debug] 74.031777 DEBUG : CNoCheatZPlugin::ClientPutInServer (pEntity:0xee6b706c -> pEntity->classname:, playername:Iwi#) (Was already connected: Yes)
> [NoCheatZ v4-beta-r3-patch2-debug] 74.032019 DEBUG : CNoCheatZPlugin::ClientActive (pEntity:0xee6b706c -> pEntity->classname:player -> clientname:Iwi#)
> [NoCheatZ v4-beta-r3-patch2-debug] 74.033011 DEBUG : event player_spawn : Iwi#
> [NoCheatZ v4-beta-r3-patch2-debug] 74.033191 DEBUG : Players Iwi# : Status forced to PLAYER_CONNECTED
> [NoCheatZ v4-beta-r3-patch2-debug] 74.033918 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee6b706c -> pEntity->classname:player -> clientname:Iwi#, args:VModEnable 1)
> [NoCheatZ v4-beta-r3-patch2-debug] 78.427074 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee6b706c -> pEntity->classname:player -> clientname:Iwi#, args:joingame )
> [NoCheatZ v4-beta-r3-patch2-debug] 81.967059 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee6b706c -> pEntity->classname:player -> clientname:Iwi#, args:jointeam 2)
> [NoCheatZ v4-beta-r3-patch2-debug] 81.967887 DEBUG : event player_team
> [NoCheatZ v4-beta-r3-patch2-debug] 81.968059 DEBUG : Players Iwi# : Status forced to PLAYER_CONNECTED
> [NoCheatZ v4-beta-r3-patch2-debug] 82.986957 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee6b706c -> pEntity->classname:player -> clientname:Iwi#, args:joinclass 1)
> [NoCheatZ v4-beta-r3-patch2-debug] 82.987824 DEBUG : event round_end
> [NoCheatZ v4-beta-r3-patch2-debug] 82.988137 DEBUG : Players Nerus : Status changed from PLAYER_IN_TESTS to PLAYER_CONNECTED
> [NoCheatZ v4-beta-r3-patch2-debug] 85.973410 DEBUG : event player_spawn : Nerus
> [NoCheatZ v4-beta-r3-patch2-debug] 85.973738 DEBUG : Players Nerus : Will enter in status PLAYER_IN_TESTS in 3 seconds
> [NoCheatZ v4-beta-r3-patch2-debug] 85.975488 DEBUG : VirtualTableHook : function 0xF1E82E60 at 0xF22461BC in server_srv.so replaced by 0xEDB81792 from nocheatzX.so.
> [NoCheatZ v4-beta-r3-patch2-debug] 85.975973 DEBUG : event player_spawn : Iwi#
> [NoCheatZ v4-beta-r3-patch2-debug] 85.976293 DEBUG : Players Iwi# : Will enter in status PLAYER_IN_TESTS in 3 seconds
> [NoCheatZ v4-beta-r3-patch2-debug] 85.991879 DEBUG : VirtualTableHook : function 0xF1E82E60 at 0xF2241A9C in server_srv.so replaced by 0xEDB81792 from nocheatzX.so.
> [NoCheatZ v4-beta-r3-patch2-debug] 85.992707 ERROR : ASSERTION FAILED in Code/Misc/Helpers.cpp:237 : "Helpers::edictOfUnknown failed" && 0
> srcds_linux: Code/Misc/Helpers.cpp:237: SourceSdk::edict_t* Helpers::edictOfUnknown(void*): Assertion `"Helpers::edictOfUnknown failed" && 0' failed.
> Could not find steamerrorreporter binary. Any minidumps will be uploaded in-processOpening /home/nerus/servers/css_test/cstrike/addons/NoCheatZ/!stacktrace.txt
> /home/buildbot/buildslave/steam_rel_client_linux/build/src/tier1/../tier1/fileio.cpp (3997) : Assertion Failed: CFileWriterThread: pending file writer content_log.txt
> Assert( Assertion Failed: CFileWriterThread: pending file writer content_log.txt ):/home/buildbot/buildslave/steam_rel_client_linux/build/src/tier1/../tier1/fileio.cpp:3997
> 
> Uploading dump (in-process) [proxy '']
> /tmp/dumps/crash_20170407202630_8.dmp
> success = no
> error:  libcurl.so: cannot open shared object file: No such file or directory
> /home/buildbot/buildslave/steam_rel_client_linux/build/src/tier1/../tier1/fileio.cpp (3997) : Assertion Failed: CFileWriterThread: pending file writer connection_log_27016.txt
> /home/buildbot/buildslave/steam_rel_client_linux/build/src/tier1/../tier1/fileio.cpp (3997) : Assertion Failed: CFileWriterThread: pending file writer stats_log.txt
> Bad thread local/home/buildbot/buildslave/steam_rel_client_linux/build/src/tier0/threadtools.cpp (1431) : Assertion Failed: Thread synchronization object is unuseable
> Bad thread local
