### ISSUE TITLE
[CSS] Server crashes

### ISSUE THREAD

**Issue by Nerus87** [L-EARN/NoCheatZ-4#131]
Couple time server crash on dust2.

Sourcemod.
Source_TV enabled.

> 12/16/16 19:32:32 [ Server Tick #300] PLAYING ON A NEW MAP : de_dust2
> 12/16/16 19:34:03 [ Server Tick #27358] Player connect : Nerus []
> 12/16/16 19:35:27 [ Server Tick #300] PLAYING ON A NEW MAP : de_dust2
> 12/16/16 19:35:27 [ Server Tick #301] Player connect : Nerus []
> 12/16/16 19:36:33 [ Server Tick #300] PLAYING ON A NEW MAP : de_dust2
> 12/16/16 19:36:46 [ Server Tick #3995] WARNING : VirtualTableHook : Unexpected virtual table value in VirtualTableHook. Module sourcemod.2.css.so might be in conflict.
> 12/16/16 19:36:46 [ Server Tick #3995] WARNING : VirtualTableHook : Unexpected virtual table value in VirtualTableHook. Module sourcemod.2.css.so might be in conflict.

P.S. please give me feedback what information's you need.

**Comment by Nerus87** [comment]
> 12/16/16 19:36:46 [ Server Tick #3995] WARNING : VirtualTableHook : Unexpected virtual table value in VirtualTableHook. Module sourcemod.2.css.so might be in conflict.

Will not working with sourcemod ?

**Comment by L-EARN** [comment]
Hi,

Sorry for the very very late answer, the development of the plugin was aborted.
NoCheatZ was designed to run as a single plugin on the server. Although I did all my possible to detect any compatibility issue in the code and tryed to fix it, it didn't work as you see.

The dev MIGHT be going on soon and integrate Metamod, either directly or inderectly.
I MAYBE will do this or if someone do it as a fork I will integrate it too.

The reason behind the dev abort is I allocate less time to things that don't earn me anything, even though this project still entertain my brain (that's all I want) ...

**Comment by Nerus87** [comment]
The new crash occurred at server (with metamod and sourcemod).

> > [NoCheatZ v4-beta-r4] 124.107193 DEBUG : Bypassed ConCommand autobuy of Nerus
> 
> [NoCheatZ v4-beta-r4] 124.107936 DEBUG : VirtualTableHook CBaseEntity::SetTransmit: function 0xF1E80E60 at 0xF2241FDC in server_srv.so replaced by 0xEDAE23C8 from nocheatzX.so.
> [NoCheatZ v4-beta-r4] 146.383132 DEBUG : event player_death : Ethan
> [Spawn Control] DEBUG | OnPlayerDeath() | Can't respawn player, is standard round.
> [NoCheatZ v4-beta-r4] 150.222023 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee6b5044 -> pEntity->classname:player -> clientname:Nerus, args:drop )
> [NoCheatZ v4-beta-r4] 150.225195 ERROR : ASSERTION FAILED in Code/Misc/Helpers.cpp:237 : "Helpers::edictOfUnknown failed" && 0
> srcds_linux: Code/Misc/Helpers.cpp:237: SourceSdk::edict_t* Helpers::edictOfUnknown(void*): Assertion `"Helpers::edictOfUnknown failed" && 0' failed.
> Could not find steamerrorreporter binary. Any minidumps will be uploaded in-processOpening /home/nerus/servers/css_test/cstrike/addons/NoCheatZ/!stacktrace.txt
> /home/buildbot/buildslave/steam_rel_client_linux/build/src/tier1/../tier1/fileio.cpp (3997) : Assertion Failed: CFileWriterThread: pending file writer content_log.txt
> Assert( Assertion Failed: CFileWriterThread: pending file writer content_log.txt ):/home/buildbot/buildslave/steam_rel_client_linux/build/src/tier1/../tier1/fileio.cpp:3997
> 
> Uploading dump (in-process) [proxy '']
> /tmp/dumps/crash_20170604233213_8.dmp
> success = no
> error:  libcurl.so: cannot open shared object file: No such file or directory
> /home/buildbot/buildslave/steam_rel_client_linux/build/src/tier1/../tier1/fileio.cpp (3997) : Assertion Failed: CFileWriterThread: pending file writer connection_log_27016.txt
> /home/buildbot/buildslave/steam_rel_client_linux/build/src/tier1/../tier1/fileio.cpp (3997) : Assertion Failed: CFileWriterThread: pending file writer stats_log.txt
> Bad thread local/home/buildbot/buildslave/steam_rel_client_linux/build/src/tier0/threadtools.cpp (1431) : Assertion Failed: Thread synchronization object is unuseable
> Bad thread local

**Comment by L-EARN** [comment]
Hi,

It comes from the WallhackBlocker module.
I see it happen right after you drop a weapon ; do you have some kind of weapon removal plugin ?

**Comment by Nerus87** [comment]
Basically, I've to try run the SRCDS with basics Sourcemod plugins (provided with sm).

Maybe the problem is when I was kicked by the server for BunnyHop ?
