### ISSUE TITLE
Can't Compile on Ubuntu 14.04 Still

### ISSUE THREAD

**Issue by Sandman007** [L-EARN/NoCheatZ-4#14]
Me again. I tried compiling this morning. Still cant compile. Here is what I did:

`git clone -b master --single-branch https://github.com/L-EARN/NoCheatZ-4 NewNoCheatZ-4`
`cd NewNoCheatZ-4/server-plugin/ && git submodule update --init`
`sudo make release`

Error in Console:
`sudo make release
make[1]: Entering directory `/home/tyler/Desktop/NewNoCheatZ-4/server-plugin'
Updating protobuf 2.5.0
make[2]: Entering directory `/home/tyler/Desktop/NewNoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0'
make[2]: *** No targets specified and no makefile found.  Stop.
make[2]: Leaving directory `/home/tyler/Desktop/NewNoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0'
Configuring protobuf 2.5.0
+ sed -i -e s/RuntimeLibrary="5"/RuntimeLibrary="3"/g;
           s/RuntimeLibrary="4"/RuntimeLibrary="2"/g; gtest/msvc/gtest-md.vcproj gtest/msvc/gtest.vcproj gtest/msvc/gtest_main-md.vcproj gtest/msvc/gtest_main.vcproj gtest/msvc/gtest_prod_test-md.vcproj gtest/msvc/gtest_prod_test.vcproj gtest/msvc/gtest_unittest-md.vcproj gtest/msvc/gtest_unittest.vcproj
+ autoreconf -f -i -Wall,no-obsolete
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
../scripts/make-protobuf.sh: 23: ../scripts/make-protobuf.sh: ./configure: not found
Building protobuf 2.5.0
make[2]: Entering directory `/home/tyler/Desktop/NewNoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0'
make[2]: *** No targets specified and no makefile found.  Stop.
make[2]: Leaving directory `/home/tyler/Desktop/NewNoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0'
make[1]: *** [prepare-build] Error 2
make[1]: Leaving directory `/home/tyler/Desktop/NewNoCheatZ-4/server-plugin'
make: *** [release] Error 2`

It seemed to compile all files. I have a these files:
/home/tyler/Desktop/NewNoCheatZ-4/Builds/Release/addons/NoCheatZ/nocheatz.vdf
/home/tyler/Desktop/NewNoCheatZ-4/Builds/Release/addons/NoCheatZ/config.ini
/home/tyler/Desktop/NewNoCheatZ-4/Builds/Release/cfg/nocheatz.cfg

Am I missing a file? 

Thanks
Sandman007

**Comment by L-EARN** [comment]
Hi,

Here is your error : `Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326. autoreconf: failed to run aclocal: No such file or directory`

One package seems to be missing in your new system.

Try to run `sudo apt-get install automake`

**Comment by Sandman007** [comment]
That seemed to have worked! Thanks. If I may I would suggest adding that to the Readme/Install Instructions on your Project Home Page. I did not know that was a requirement and it does not seem to come preinstalled on Ubuntu 14.04. 

I guess you can close this unless you want to keep it open until I can test the plugin on my server later today/tonight. Thanks for your help as always L-EARN!
