### ISSUE TITLE
Compiling problem on Debian 8.4

### ISSUE THREAD

**Issue by AJIekceu4** [L-EARN/NoCheatZ-4#15]
Hello, trying to compile this anticheat to test on my server, but got error message.
3.16.0-4-amd64
...
 Code/Systems/Testers/JumpTester.cpp =>  Debug/Code/Systems/Testers/JumpTester.o
 Code/Systems/Testers/SpeedTester.cpp =>  Debug/Code/Systems/Testers/SpeedTester.o
 Code/Systems/Testers/ValidationTester.cpp =>  Debug/Code/Systems/Testers/ValidationTester.o
Makefile:127: recipe for target 'Debug/Code/Systems/Testers/ValidationTester.o' failed
make[1]: *** [Debug/Code/Systems/Testers/ValidationTester.o] Error 1
make[1]: Leaving directory '/srv/NoCheatZ-4/server-plugin'
Makefile:140: recipe for target 'debug' failed
make: *** [debug] Error 2
...

error_compile.txt:
///
In file included from ../server-plugin/SourceSdk/Console/convar.h:4:0,
                 from ../server-plugin/Code/Systems/BaseSystem.h:23,
                 from Code/Systems/Testers/ValidationTester.h:20,
                 from Code/Systems/Testers/ValidationTester.cpp:18:
../server-plugin/SourceSdk/SdkPreprocessors.h: In function ‘void Destruct(T*)’:
../server-plugin/SourceSdk/SdkPreprocessors.h:408:58: warning: there are no arguments to ‘memset’ that depend on a template parameter, so a declaration of ‘memset’ must be available [-fpermissive]
  memset(reinterpret_cast<void*>(pMemory), 0xDD, sizeof(T));
                                                          ^
Code/Systems/Testers/ValidationTester.cpp: At global scope:
Code/Systems/Testers/ValidationTester.cpp:127:6: error: prototype for ‘void ValidationTester::ProcessOnTick(float)’ does not match any in class ‘ValidationTester’
 void ValidationTester::ProcessOnTick(float const curtime)
      ^
In file included from Code/Systems/Testers/ValidationTester.cpp:18:0:
Code/Systems/Testers/ValidationTester.h:106:7: error: candidate is: virtual void ValidationTester::ProcessOnTick()
  void ProcessOnTick();
       ^
///

**Comment by L-EARN** [comment]
Hi,

Thanks for reporting this.
You can now pull the new version of master and try again.

`git pull origin master`

Feel free to post any other thing by [creating a new issue](https://github.com/L-EARN/NoCheatZ-4/issues/new).
