### ISSUE TITLE
sm_ban ban reason

### ISSUE THREAD

**Issue by rogeraabbccdd** [L-EARN/NoCheatZ-4#151]
You're not forced to complete all the followings, but any detail can help.

### The name of the game your server is running on.
CSGO

### The version of the plugin release (R) 
NoCheatZ v4.0.0 r7, "Release.tar.gz".

### Are you using other mods (list please) ?
Sourcemod
Sourcebans++1.6.2-git522

### Are you using a listen server or a dedicated server ?
Linux Dedicated server

### Is the server localhost, LAN or remote ? Using Steam ? (A connect-link to a test-server is allowed)
Using Steam, not lan server.

### Expected behavior
Just an example:
EyeAnglesTester triggered a detection : Using a No recoil.

### Current behavior ?
Current ban reason:
sm_ban clientindex 0

### Steps to reproduce the problem ?
Install metamod and sourcemod.
Install sourcebans?
Trigger NoCheatZ detection.

**Comment by L-EARN** [comment]
Hi,

I don't understand. Is the ban reason empty ?

**Comment by Weeeishy** [comment]
From what I've understood.

Currently when someone gets banned. The ban reason will show up as "clientindex 0" which is confusing since you want to know why they got banned. So what he's suggesting is to change the reason of the ban to something like this "EyeAnglesTester triggered a detection : Using a No recoil."

**Comment by rogeraabbccdd** [comment]
The ban reason is something like `sm_ban #3 0` now.

**Comment by rsgua** [comment]
me too everyone ban for this reasron

**Comment by rsgua** [comment]
sm_ban #45 0 sm_ban #45 0 sm_ban #45 0 sm_ban #45 0 sm_ban

**Comment by rsgua** [comment]
logs http://in-g.su/1.rar
