### ISSUE TITLE
Crashing upon map change

### ISSUE THREAD

**Issue by Weeeishy** [L-EARN/NoCheatZ-4#158]
You're not forced to complete all the followings, but any detail can help.

### The name of the game your server is running on and the version of the game.

CSGO, latest update.

### The version of the plugin release (R) (Otherwise, link to commit/pull request/fork). If using a custom build, please list your compiler version, your server and builder OS versions.

NoCheatZ v4.0.5 r8

### Are you using other mods (list please) ?

Metamod:Source version 1.10.7-dev
SourceMod Version: 1.8.0.5998

### Are you using a listen server or a dedicated server ?

Windows 2012 server dedicated server

### Is the server localhost, LAN or remote ? Using Steam ? (A connect-link to a test-server is allowed)

Steam server

### Expected behavior ?
Changes map without crashing

### Current behavior ? (You can link a demo/video and logfiles. Don't forget to strip personnal and sensitive informations before.)

After the map changes, it just crashes and doesn't load the new map

### Steps to reproduce the problem ?

Change the map

Whole console log can be found here: https://pastebin.com/vBFDbekH

Thank you.

**Comment by Weeeishy** [comment]
By the way, even when I disable the auto-recording feature in both of the cfg and config, it still records. No idea why.

**Comment by L-EARN** [comment]
There is nothing alarming in this log.
Can I have the last log from nocheatz and not from the server ?

**Comment by Weeeishy** [comment]
Hi,

Basically thats what I've got for the logs on 13th which was the latest. (full)
https://pastebin.com/F8nqSHSN

Also the !stacktrace.txt file is always empty. Never seen any logs in it.

**Comment by L-EARN** [comment]
I don't see any error and I can not replicate the crash.

Maybe you can send me a minidump file (same directory as srcds.exe) if they are not also empty ?

**Comment by Weeeishy** [comment]
I'm sorry, I didn't find any minidump files in the directory. I know I'm not providing any useful info, but I'm sending all the logs I have. Is there anything you advice to do?

**Comment by L-EARN** [comment]
Describe me the most precisely how you discovered this crash.

(Moment, number of players, timed out, you were in game or using hlsw, your game was actually going to the next level or did the server crashed before, how much times you were able to change a level before the crash happen, can you identify a conflicting plugin, etc)

I'm thinking ... Maybe metamod catched the crash. Look in that way please ...

**Comment by Weeeishy** [comment]
Here are 3 different scenarios that crashes the server.

1- Wait for mp_maxrounds or mp_timelimit to end so a new map loads then it crashes.
2- An admin force changes the map and it crashes while loading the map.
3- Players do an RTV (Rock The Vote) to change the map and it also crashes while loading the new map.

As I said, it happens on my Windows 2012 server, I don't have a Linux server so I can't reproduce it there.

**Comment by L-EARN** [comment]
Did you also had this issue with previous versions of NoCheatZ ?
Can you identify a previous version of NoCheatZ that is not affected by this issue ?

**Comment by Weeeishy** [comment]
R6 and below will just crash when I choose a team. R7 is doing the same thing as R8. I've tried the debug version and ended up with crashing the server, but with the debug version the stacktrace file catched the crash. 

https://pastebin.com/2TB0JF8f



Also, after couple of testing. I figured out that map change isn't the issue, the issue is when players reconnect to the game. For an example, when I'm in the server and I type "retry" or just disconnect and join manually, it will insta crash.


Hope this helps.

**Comment by Weeeishy** [comment]
Ok seems like I figured out the cause. 


After I ran the debug version, I've noticed that accelerator (https://forums.alliedmods.net/showthread.php?t=277703) catched a crash which can be found here: https://crash.limetech.org/kgckny6aosxy

that gave me a hint to the PTAH exention it self, but when I unloaded it I got the same results. So I unloaded a plugin that depends on it which can be found also here: https://forums.alliedmods.net/showthread.php?t=297604 and the "retry" crashed didnt happen while loading the map, instead the map loaded fine, but when I join a team the server crashed. I kept unloading other plugins and I found out there is another plugin that is conflicting with NoCheatz which is afk manager https://forums.alliedmods.net/showthread.php?p=708265


So after unloading both of the plugins, the server was stable and running fine.


Conflicting SourceMod plugins:
1- Stealth Revived: https://forums.alliedmods.net/showthread.php?t=297604
2- AFK Manager: https://forums.alliedmods.net/showthread.php?p=708265


Hopefully there will be a work around for that problem.

**Comment by L-EARN** [comment]
I've talked with the developer of Stealth Revived last week and he is ok I implement his work in nocheatz.
This would be the only stable solution to stay compatible, because this plugin is overriding important parts of WallhackBlocker. Implementing this will require a lot of work.

For AFK Manager, I will test and see what I can do.

Thank you.

**Comment by Weeeishy** [comment]
Sounds good! I've noticed incompatibility issue with plugins that changes your knife (!knife) or changes the color of your skin (!ws), where it prevents it from changing anything. But that doesn't affect or crashes the server. Just thought of mentioning it.



Thanks for your hard work, I really do appreciate it. Keep up the good work!

**Comment by L-EARN** [comment]
Hi,

Still can't crash with afk manager. I need your configuration files for this plugin and for nocheatz, please.
Are you also using colored text for this ?

**Comment by Weeeishy** [comment]
Hello,

afk_manager.cfg
https://pastebin.com/dMssHDLa

nocheatz.cfg
https://pastebin.com/279Nw61y

config.ini
https://pastebin.com/U28LB7Vw


type "retry" in console while you're in the server, or just wait for the afk manager to kick you and reconnect.

I don't get what do you mean by colored text, sorry!

**Comment by L-EARN** [comment]
By colored I mean you can use colored chat message with AFK Manager.
I guess you use it since you have sm_afk_prefix_color "1".

But this plugin is weird. It starts couting when I join the server, loading my map. But it must not process dead players or spectators with this config file. 
If I'm not fast enough I get kicked before I even choose a team. You should report this. 

No crash still ... I'm missing something.

**Comment by L-EARN** [comment]
Hi,

I got someone else with this issue.

Still investigating.

**Comment by Weeeishy** [comment]
Hello,

That some good news. Hopefully, you'll be able to track down the issue! If you need any information or testing then please let me know!


Goodluck

**Comment by Weeeishy** [comment]
Awesome. I will test out the new build and see how it goes!


Thanks
