### ISSUE TITLE
BhopBlocker, players "stick" to the ground

### ISSUE THREAD

**Issue by T1MOXA** [L-EARN/NoCheatZ-4#163]
When enabled BhopBlocker players complain that they stick to the ground when jumping.

**Comment by L-EARN** [comment]
Hi,

I tested it. And everything is working as expected : The jump command is blocked for a short period of time when the players lands on ground. So they cannot jump during this short period, and they are stuck.

That's exactly how the bhopblocker is supposed to work.

**Comment by T1MOXA** [comment]
The usual players complaining about it.
I think it should not be.

**Comment by T1MOXA** [comment]
How to do it ?
git clone ?
