### ISSUE TITLE
BAN_ASYNC - not wait at all

### ISSUE THREAD

**Issue by TR1D** [L-EARN/NoCheatZ-4#170]
Dedicated csgo server, steam, no mods
NoCheatZ v4 r10, debian

nocheatz.cfg

```
ncz EyeAnglesTester enable
ncz EyeAnglesTester SetAction BAN_ASYNC
```
If you pay attention to logs in #169, there is no waiting before the ban.

**Comment by L-EARN** [comment]
It waits.

21:25:59 first detection - 21:26:09 kick.

10 seconds.
