### ISSUE TITLE
Ncz does not run on server start

### ISSUE THREAD

**Issue by hooliganxxx** [L-EARN/NoCheatZ-4#181]
Game: CSGO
Version: R30
Mods: metamod, sourcemod

Well, what I did is put the compiled version into csgo server directory /csgo/
what was in addons went to addons folder, nocheats.cfg to cfg folder,
new logs directory was created as well as auto tv records. - just like you can see on the screenshots I attached.

However when I run the server, ncz does not run with it. 
Whenever I type in console ncz - it says unknown command....

Did I install it in a wrong way?
Thanks! I really want to run and test these, please help me out!

![1](https://user-images.githubusercontent.com/30504700/28681755-45bcac74-7303-11e7-9399-c43ec6a55bd3.PNG)
![2](https://user-images.githubusercontent.com/30504700/28681754-45bc65fc-7303-11e7-8bd3-1e1db7085cfa.PNG)
![3](https://user-images.githubusercontent.com/30504700/28681756-45be5600-7303-11e7-9562-e6581384f04a.PNG)
![4](https://user-images.githubusercontent.com/30504700/28681757-45c09000-7303-11e7-992d-6ab517812214.PNG)

**Comment by L-EARN** [comment]
Hi,

Can you start your server with `-condebug -condump` commandline options and send me the content of `/home/ogp_agent/OGP_User_Files/46/csgo/console.log` please ?

**Comment by hooliganxxx** [comment]
sure, here you go
``
#
#Console initialized.
#Using breakpad minidump system 740/13595.550.DC
#Game.dll loaded for "Counter-Strike: Global Offensive"
#CGameEventManager::AddListener: event 'server_pre_shutdown' unknown.
#CGameEventManager::AddListener: event 'game_newmap' unknown.
#CGameEventManager::AddListener: event 'finale_start' unknown.
#CGameEventManager::AddListener: event 'round_start' unknown.
#CGameEventManager::AddListener: event 'round_end' unknown.
#CGameEventManager::AddListener: event 'difficulty_changed' unknown.
#CGameEventManager::AddListener: event 'player_connect' unknown.
#CGameEventManager::AddListener: event 'player_disconnect' unknown.
Failed to load gamerulescvars.txt, game rules cvars might not be reported to management tools.
Server is hibernating
Particles: Missing 'particles/money_fx.pcf'
 failed to dlopen /home/ogp_agent/OGP_User_Files/46/csgo/addons/NoCheatZ/nocheatzX.so error=/lib/i386-linux-gnu/i686/cmov/libc.so.6: version `GLIBC_2.17' not found (required by /home/ogp_agent/OGP_User_Files/46/csgo/addons/NoCheatZ/nocheatzX.so)
Unable to load plugin "addons/NoCheatZ/nocheatzX"
maxplayers set to 64
Skirmish mode 6 references a non-existant gamemode: deathmatch
Skirmish mode 7 references a non-existant gamemode: deathmatch
ConVarRef cl_embedded_stream_video_playing doesn't point to an existing ConVar
Unknown command "cl_bobamt_vert"
Unknown command "cl_bobamt_lat"
Unknown command "cl_bob_lower_amt"
Unknown command "cl_viewmodel_shift_left_amt"
Unknown command "cl_viewmodel_shift_right_amt"
Unknown command "cl_teamid_min"
Unknown command "cl_teamid_max"
Unknown command "cl_teamid_overhead"
Unknown command "cl_teamid_overhead_maxdist"
Setting mapgroup to 'mg_bomb'
--------------------------------------------------------
sv_pure set to 0.
--------------------------------------------------------
---- Host_NewGame ----
ConVarRef r_staticlight_streams_indirect_only doesn't point to an existing ConVar
Host_NewGame on map de_dust2
L 07/28/2017 - 07:10:39: -------- Mapchange to de_dust2 --------
L 07/28/2017 - 07:10:40: [GEOIP] GeoIP database info: GEO-106FREE 20170606 Build 1 Copyright (c) 2017 MaxMind Inc All Rights Reserved
CGameEventManager::AddListener: event 'teamplay_win_panel' unknown.
CGameEventManager::AddListener: event 'teamplay_restart_round' unknown.
CGameEventManager::AddListener: event 'arena_win_panel' unknown.
L 07/28/2017 - 07:10:41: [simple-chatprocessor.smx] [SCP] Recognized mod [Counter-Strike: GO].
L 07/28/2017 - 07:10:41: [simple-chatprocessor.smx] [SCP] Loading translation file [scp.csgo.phrases].
ConVarRef room_type doesn't point to an existing ConVar
ammo_grenade_limit_default - 1
ammo_grenade_limit_flashbang - 1
ammo_grenade_limit_total - 3
bot_allow_grenades - 1
bot_allow_machine_guns - 1
bot_allow_pistols - 1
bot_allow_rifles - 1
bot_allow_rogues - 1
bot_allow_shotguns - 1
bot_allow_snipers - 1
bot_allow_sub_machine_guns - 1
bot_autodifficulty_threshold_high - 5.0
bot_autodifficulty_threshold_low - -2.0
bot_chatter - normal
bot_defer_to_human_goals - 0
bot_defer_to_human_items - 1
bot_difficulty - 1
bot_quota - 10
bot_quota_mode - normal
cash_player_bomb_defused - 300
cash_player_bomb_planted - 300
cash_player_damage_hostage - -30
cash_player_get_killed - 0
cash_player_interact_with_hostage - 150
cash_player_killed_enemy_default - 300
cash_player_killed_enemy_factor - 1
cash_player_killed_hostage - -1000
cash_player_killed_teammate - -300
cash_player_rescued_hostage - 1000
cash_player_respawn_amount - 0
cash_team_elimination_bomb_map - 3250
cash_team_elimination_hostage_map_ct - 2000
cash_team_elimination_hostage_map_t - 1000
cash_team_hostage_alive - 0
cash_team_hostage_interaction - 500
cash_team_loser_bonus - 1400
cash_team_loser_bonus_consecutive_rounds - 500
cash_team_planted_bomb_but_defused - 800
cash_team_rescued_hostage - 0
cash_team_survive_guardian_wave - 1000
cash_team_terrorist_win_bomb - 3500
cash_team_win_by_defusing_bomb - 3250
cash_team_win_by_hostage_rescue - 3500
cash_team_win_by_time_running_out_bomb - 3250
cash_team_win_by_time_running_out_hostage - 3250
ff_damage_reduction_bullets - 0.1
ff_damage_reduction_grenade - 0.25
ff_damage_reduction_grenade_self - 1
ff_damage_reduction_other - 0.25
global_chatter_info - 
mp_afterroundmoney - 0
mp_anyone_can_pickup_c4 - 0
mp_autoteambalance - 1
mp_buy_allow_grenades - 1
mp_buy_allow_guns - 255
mp_buy_anywhere - 0
mp_buy_during_immunity - 0
mp_buytime - 90
mp_c4_cannot_be_defused - 0
mp_c4timer - 40
mp_consecutive_loss_max - 4
mp_coop_force_join_ct - 0
mp_coopmission_bot_difficulty_offset - 0
mp_coopmission_mission_number - 0
mp_ct_default_grenades - 
mp_ct_default_melee - weapon_knife
mp_ct_default_primary - 
mp_ct_default_secondary - weapon_hkp2000
mp_damage_headshot_only - 0
mp_damage_scale_ct_body - 1.0
mp_damage_scale_ct_head - 1.0
mp_damage_scale_t_body - 1.0
mp_damage_scale_t_head - 1.0
mp_damage_vampiric_amount - 0
mp_death_drop_c4 - 1
mp_death_drop_defuser - 1
mp_death_drop_grenade - 2
mp_death_drop_gun - 1
mp_deathcam_skippable - 1
mp_default_team_winner_no_objective - -1
mp_defuser_allocation - 0
mp_display_kill_assists - 1
mp_dm_bonus_percent - 50
mp_dm_bonus_respawn - 0
mp_dm_bonusweapon_dogtags - 0
mp_dm_dogtag_score - 0
mp_dm_kill_base_score - 10
mp_dm_teammode - 0
mp_dm_teammode_bonus_score - 1
mp_dm_teammode_dogtag_score - 0
mp_dm_teammode_kill_score - 1
mp_dogtag_despawn_on_killer_death - 1
mp_dogtag_despawn_time - 120
mp_dogtag_pickup_rule - 0
mp_economy_reset_rounds - 0
mp_equipment_reset_rounds - 0
mp_force_assign_teams - 0
mp_force_pick_time - 15
mp_forcecamera - 1
mp_free_armor - 0
mp_freezetime - 6
mp_friendlyfire - 0
mp_ggprogressive_round_restart_delay - 15.0
mp_ggtr_always_upgrade - 0
mp_ggtr_bomb_defuse_bonus - 1
mp_ggtr_bomb_detonation_bonus - 1
mp_ggtr_bomb_pts_for_flash - 4
mp_ggtr_bomb_pts_for_he - 3
mp_ggtr_bomb_pts_for_molotov - 5
mp_ggtr_bomb_pts_for_upgrade - 2.0
mp_ggtr_bomb_respawn_delay - 0.0
mp_ggtr_end_round_kill_bonus - 1
mp_ggtr_halftime_delay - 0.0
mp_ggtr_last_weapon_kill_ends_half - 0
mp_give_player_c4 - 1
mp_global_damage_per_second - 0.0
mp_guardian_bot_money_per_wave - 800
mp_guardian_loc_adjective - 
mp_guardian_loc_condition - 
mp_guardian_loc_icon - 
mp_guardian_loc_mission - default
mp_guardian_loc_override - 
mp_guardian_loc_weapon - 
mp_guardian_player_dist_max - 2000
mp_guardian_player_dist_min - 1300
mp_guardian_special_kills_needed - 10
mp_guardian_special_weapon_needed - awp
mp_guardian_target_site - -1
mp_halftime - 0
mp_halftime_pausetimer - 0
mp_heavyassaultsuit_cooldown - 5
mp_hostagepenalty - 10
mp_hostages_max - 2
mp_hostages_spawn_force_positions - 
mp_hostages_spawn_same_every_round - 1
mp_items_prohibited - 
mp_limitteams - 2
mp_match_can_clinch - 1
mp_max_armor - 2
mp_maxmoney - 16000
mp_maxrounds - 0
mp_molotovusedelay - 15.0
mp_playercashawards - 1
mp_radar_showall - 0
mp_randomspawn - 0
mp_randomspawn_dist - 0
mp_randomspawn_los - 1
mp_respawn_immunitytime - 4.0
mp_respawn_on_death_ct - 0
mp_respawn_on_death_t - 0
mp_respawnwavetime_ct - 10.0
mp_respawnwavetime_t - 10.0
mp_round_restart_delay - 7.0
mp_roundtime - 5
mp_roundtime_defuse - 0
mp_roundtime_hostage - 0
mp_solid_teammates - 1
mp_starting_losses - 0
mp_startmoney - 800
mp_t_default_grenades - 
mp_t_default_melee - weapon_knife
mp_t_default_primary - 
mp_t_default_secondary - weapon_glock
mp_taser_recharge_time - -1
mp_teamcashawards - 1
mp_teammates_are_enemies - 0
mp_timelimit - 5
mp_use_respawn_waves - 0
mp_warmup_pausetimer - 0
mp_warmuptime - 30
mp_warmuptime_all_players_connected - 0
mp_weapon_self_inflict_amount - 0
mp_weapons_allow_heavy - -1
mp_weapons_allow_heavyassaultsuit - 0
mp_weapons_allow_map_placed - 0
mp_weapons_allow_pistols - -1
mp_weapons_allow_rifles - -1
mp_weapons_allow_smgs - -1
ConVarRef mp_weapons_allow_tagrenade doesn't point to an existing ConVar
mp_weapons_allow_typecount - 5
mp_weapons_allow_zeus - 1
mp_weapons_glow_on_ground - 0
mp_weapons_max_gun_purchases_per_weapon_per_match - -1
mp_win_panel_display_time - 3
occlusion_test_async - 0
spec_freeze_panel_extended_time - 0.0
spec_freeze_time - 3.0
spec_replay_enable - 0
sv_accelerate - 5.5
sv_airaccelerate - 12
sv_allow_votes - 1
sv_alltalk - 0
sv_arms_race_vote_to_restart_disallowed_after - 0
sv_auto_adjust_bot_difficulty - 1
sv_auto_full_alltalk_during_warmup_half_end - 1
sv_autobunnyhopping - 0
sv_autobuyammo - 0
sv_bot_buy_decoy_weight - 1
sv_bot_buy_flash_weight - 1
sv_bot_buy_grenade_chance - 33
sv_bot_buy_hegrenade_weight - 6
sv_bot_buy_molotov_weight - 1
sv_bot_buy_smoke_weight - 1
sv_bots_force_rebuy_every_round - 0
sv_bots_get_easier_each_win - 0
sv_bots_get_harder_after_each_wave - 0
sv_bounce - 0
sv_buy_status_override - -1
sv_deadtalk - 0
sv_disable_show_team_select_menu - 0
sv_duplicate_playernames_ok - 0
sv_enablebunnyhopping - 0
sv_friction - 5.2
sv_gravity - 800
sv_guardian_heavy_all - 0
sv_guardian_heavy_count - 0
sv_guardian_max_wave_for_heavy - 0
sv_guardian_min_wave_for_heavy - 0
sv_ignoregrenaderadio - 0
sv_infinite_ammo - 0
sv_maxspeed - 320
sv_maxvelocity - 3500
sv_occlude_players - 1
sv_staminajumpcost - .080
sv_staminalandcost - .050
sv_stopspeed - 80
sv_talk_enemy_dead - 0
sv_talk_enemy_living - 0
sv_vote_to_changelevel_before_match_point - 0
sv_wateraccelerate - 10
sv_waterfriction - 1
tv_delay - 10
weapon_accuracy_nospread - 0
weapon_air_spread_scale - 1.0
ConVarRef weapon_cleanup_on_round_restart doesn't point to an existing ConVar
weapon_max_before_cleanup - 0
weapon_recoil_scale - 2.0
weapon_reticle_knife_show - 0
ff_damage_reduction_grenade - 0.25
ff_damage_reduction_grenade_self - 1
ff_damage_reduction_other - 0.25
mp_friendlyfire - 0
mp_warmuptime - 30
mp_warmuptime_all_players_connected - 0
Executing dedicated server config file
Stopping 0 worker threads
Starting 1 worker threads
3 threads. 1,213,754 ticks
Note that cmd line -threads 4 is specified
Stopping 3 worker threads
Starting 1 worker threads
3 threads. 1,042,171,274 ticks
Note that cmd line -threads 4 is specified
Stopping 3 worker threads
Starting 1 worker threads
3 threads. 783,699,192 ticks
Note that cmd line -threads 4 is specified
Stopping 3 worker threads
Starting 1 worker threads
3 threads. 1,043,304,073 ticks
Note that cmd line -threads 4 is specified
Stopping 3 worker threads
Starting 1 worker threads
3 threads. 782,920,862 ticks
Note that cmd line -threads 4 is specified
Commentary: Could not find commentary data file 'maps/de_dust2_commentary.txt'. 
[SourceBans++] Loading configs/sourcebans.cfg config file
[SourceComms++] Loading configs/sourcebans/sourcebans.cfg config file
[SourceComms++] Loading configs/sourcecomms.cfg config file
Initializing Steam libraries for secure Internet server
Logging into Steam gameserver account with logon token '21A46C9Axxxxxxxxxxxxxxxxxxxxxxxx'
Connection to Steam servers successful.
   Public IP is 37.230.210.83.
Assigned persistent gameserver Steam ID [G:1:1365670].
VAC secure mode is activated.
GC Connection established for server version 550, instance idx 1
Client "x_X_Fantom_X_x" connected (188.130.176.23:27005).
Server waking up from hibernation
Client "the dark man" connected (41.230.59.38:27005).
Client "MAFAKA" connected (91.213.59.20:27005).
Dropped the dark man from server: You have been banned by this server, check http://vk.com/csderzkiy for more info
Client "KOT9" connected (91.107.98.37:47081).
Client "<в–“waСЏtв–“>" connected (84.117.182.67:27005).
PutClientInServer: no info_player_start on level
PutClientInServer: no info_player_start on level
Client "HomePC" connected (95.188.185.184:27005).
Client "Е¦С’С”в‰€ГѕВ®Гё" connected (178.121.62.224:7182).
Late precache of particle/smokestack.vmt
PutClientInServer: no info_player_start on level
Client "< blank >" connected (178.121.187.26:39339).
PutClientInServer: no info_player_start on level
Client "nosTEAM-player" connected (94.219.188.183:27005).
Client "РµР¶Р¶Рё" connected (85.140.4.90:61173).
PutClientInServer: no info_player_start on level
PutClientInServer: no info_player_start on level
PutClientInServer: no info_player_start on level
PutClientInServer: no info_player_start on level
Client "С…Р°РІС‡РёРє" connected (37.144.132.151:27005).
PutClientInServer: no info_player_start on level
Client "TriaN" connected (37.112.36.253:27005).
PutClientInServer: no info_player_start on level
PutClientInServer: no info_player_start on level
``

**Comment by hooliganxxx** [comment]
ok here is the source of the problm
```
 failed to dlopen /home/ogp_agent/OGP_User_Files/46/csgo/addons/NoCheatZ/nocheatzX.so error=/lib/i386-linux-gnu/i686/cmov/libc.so.6: version `GLIBC_2.17' not found (required by /home/ogp_agent/OGP_User_Files/46/csgo/addons/NoCheatZ/nocheatzX.so)
Unable to load plugin "addons/NoCheatZ/nocheatzX"
```

**Comment by L-EARN** [comment]
You need at least glibc 2.17 on your system.
https://travis-ci.org/L-EARN/NoCheatZ-4/builds/258368810#L1594

But that's not a easy and clever task to use multiple versions of glibc on a system, and start a program with the good version can become tricky.

I'll see on my side if I can build with a lower version.

**Comment by hooliganxxx** [comment]
just checked it out my version is 2.13

**Comment by L-EARN** [comment]
Ooops. Runtime error.

**Comment by L-EARN** [comment]
Ok now it's good. The minimum required glibc version is now 2.4. You have 2.13 so you should be good.

**Comment by hooliganxxx** [comment]
thanks a lot, works just fine!
