### ISSUE TITLE
[PROBLEM] LOAD SYSTEM TO HIGHT

### ISSUE THREAD

**Issue by BlackYuzia** [L-EARN/NoCheatZ-4#193]
> System: Linux
> Version: **r56**
> Game: CS:GO
> Mods: MM, SM, PUBLIC
> System Resources: 
> ### 1x3.0Ghz AMD, RAM 2Gb,
Hello @L-EARN ,
Regarding the load on the server.
The server is hard booted / loaded with Anti-Chit.

I think **Processor** not support so big load.
Becouse you tested in **1 player and 9 bots**. I test in **1 bot (GO-TV) and 18-26 players**.

If **LIVE** players become more than 10, the server lags in places, brakes with jerks.

If **LIVE** players are more than 15
Lags and friezes become stronger.

If **LIVE** players 18-20+ - You can't play. Everything is terribly lagging and hanging.

With the specified resources, the system already with 8+ live players is loaded to 40-60+%

When **LIVE** 10+ players are loaded to 80-90%
If the players are 16-18 or more
95-99

I think the load depends very much on the number of players.
After all, every player is checked.
Simultaneously / alternately, which gives the load when a large online.

If you do not use Anti-cheat, then 20 players are free to pull.
Reaching a load of only ~ 65-75%.
If with it, % is increased by 1.3-2.0 times.

Perhaps others do not have such problems.
In connection with a more powerful system and / or for other reasons.

My settings:
[nocheatz.zip](https://github.com/L-EARN/NoCheatZ-4/files/1185726/nocheatz.zip)
Meta and plugins list:
[meta_plugins_list.zip](https://github.com/L-EARN/NoCheatZ-4/files/1185727/meta_plugins_list.zip)

Logs for the last 2 days:
[Logs(29-30).zip](https://github.com/L-EARN/NoCheatZ-4/files/1185748/Logs.29-30.zip)

You know how I can monitor load that .so (your AC)?
Or that imposible?
My firend say: 

> Such detailed statistics you nothing in the system will not.

I apologize if I got it.
I'm just trying to help improve anti-cheat :3

**Comment by BlackYuzia** [comment]
@L-EARN now, I off that AC.
Call me when fix that or call if test fix. Thanks.

**Comment by L-EARN** [comment]
What is the other anti cheat you use ?

**Comment by BlackYuzia** [comment]
@L-EARN only VAC (If that AC worked :d )
Not anythink others AC.

**Comment by BlackYuzia** [comment]
@L-EARN Your Anti-Cheat ON TIC = 128?
In my setting TIC = 64, but in net_graph 1, 
he say tic in my server = 128, up = 64, cmd = 128.
If tic = 128, server can lags and freeze.

Wnen I off AC, TIC = 64.
That bug or what?

**Comment by BlackYuzia** [comment]
@L-EARN
I find cvar in config.ini: 
> tickrate_override=128
I can change him to:
> tickrate_override=64

and yea, pls add that cvar in Readme.
Admins (who install mod) can't know that, if not research config.ini

If that all,  you can close the **issue**
