### ISSUE TITLE
Banning methods sourcemod + native

### ISSUE THREAD

**Issue by hooliganxxx** [L-EARN/NoCheatZ-4#195]
Hi, it's me again :)

The issue that I noticed is tied to banning. 
I'm using sourcemod + sourcebans wih mysql database. 
Commands to ban are sm_ban steamid.

However, some people who get banned by NCZ not only get banned this way, but also in native csgo way (banned_user.cfg, banned_ip.cfg) - and for me it is not convenient to remove those bans, as if removed manually that requires server restart. 

In the last 3 days I got 116 bans by ncz convartester, and as we agreed they could ve been false (most people just timed out) so I decided to disable this function and unban those people. After those steps, some of them still could not get on server - so I checked banned_user.cfg, banned_ip.cfg file and found a lot of people there...

If there was an option to disable native bans, or to set banning methods and length in ncz cfg file that wouldd have been really helpfull - or at least to disable an option to ban natively when sourcemod is on. Thank you for understanding!

**Comment by L-EARN** [comment]
Hi,

Actually nocheatz bans himself after sm_ban in case sourcemod did not processed the ban.
I think I'm gonna make nocheatz ban himself only when the sm_ban command is not present.

I know how much it is boring to be forced to restart the server when you got banned ...

If you want to disable writing bans into banned_user.cfg and banned_ip.cfg, you can use `ncz BanRequest AllowWriteBans No`. But it won't work if sourcemod decides to write bans.

You can also override the ban time using `ncz BanRequest SetBanTime` followed by an integer representing the minutes.

I would love to get the logs about convartester.

**Comment by hooliganxxx** [comment]
Sure, here they are attached.

[ncz logs.zip](https://github.com/L-EARN/NoCheatZ-4/files/1187283/ncz.logs.zip)
