### ISSUE TITLE
[BUG] False Ban With MouseTester_BETA?

### ISSUE THREAD

**Issue by BlackYuzia** [L-EARN/NoCheatZ-4#198]
Hi,
There's logs.
So, 2 players (nick: **Fenix** and **go v go**)
Say me: 

> We are not cheaters.
> Your Anti-Cheat suck.

They get unban. But If they really NOT use cheats and that False ban?
**Help pls**
logs:
[new 1.txt](https://github.com/L-EARN/NoCheatZ-4/files/1188260/new.1.txt)

**Comment by L-EARN** [comment]
Detections seems correct.

Do you have a tv record ?

**Comment by BlackYuzia** [comment]
@L-EARN no, I not record demos.
I record now, and you get demos.

**Comment by BlackYuzia** [comment]
@L-EARN Detections seems correct.
How I can know: That False or True ban?
You can create: Table helper or I can get info for that mousebeta?

**Comment by BlackYuzia** [comment]
@L-EARN
you say: If Delta low, and only one detect, that can be false.
Now it true or not?

> 08/01/17 13:46:37 [ Server Tick #102856, SourceTV:de_inferno-08-01-17_13-20-28.dem : Tick #100221 ] k1rch STEAM_1:0:32629878 : aimbot detected
> 08/01/17 13:46:37 [ Server Tick #102856, SourceTV:de_inferno-08-01-17_13-20-28.dem : Tick #100221 ] v4-r61-0-g031687e
> 08/01/17 13:46:37 [ Server Tick #102856, SourceTV:de_inferno-08-01-17_13-20-28.dem : Tick #100221 ] :::: MouseDetectInfo {
> :::::::: Previous Pitch Angle : 3.553057,
> :::::::: Current Pitch Angle : 3.542057 (Delta -0.011000),
> :::::::: Is Mouse Inverted ? : 0,
> :::::::: Mouse Delta Y : 1,
> :::::::: Previous Yaw Angle : 35.158184,
> :::::::: Current Yaw Angle : 32.441185 (Delta -2.716999),
> :::::::: Mouse Delta X : 25,
> :::::::: CMD Buttons : 0x20408,

And one Question.

> 08/01/17 13:22:15 [ Server Tick #9504, SourceTV:de_inferno-08-01-17_13-20-28.dem : Tick #6869 ] Player disconnect : Natus Vincere Edward [STEAM_1:0:804840977] -> Reason : You was banned by admin: CONSOLE
> Reason: "Banned by NoCheatZ 4 : aimbot"
> Ban date: 08/01/2017 - 12:58:04
> Ban length: 1 hours

He banned by reason: AIM
But, I not see log (Detect) Where he is?

**Comment by BlackYuzia** [comment]
That too right ban?
> 08/01/17 16:19:10 [ Server Tick #59701] Всякий c: STEAM_1:0:2113616184 : aimbot detected
> 08/01/17 16:19:10 [ Server Tick #59701] v4-r61-0-g031687e
> 08/01/17 16:19:10 [ Server Tick #59701] :::: MouseDetectInfo {
> :::::::: Previous Pitch Angle : 4.601470,
> :::::::: Current Pitch Angle : 4.260644 (Delta -0.340826),
> :::::::: Is Mouse Inverted ? : 0,
> :::::::: Mouse Delta Y : 3,
> :::::::: Previous Yaw Angle : -1.114348,
> :::::::: Current Yaw Angle : -1.257751 (Delta -0.143403),
> :::::::: Mouse Delta X : 0,
> :::::::: CMD Buttons : 0x400,
> ::::}
> 08/01/17 16:19:20 [ Server Tick #60344] Player disconnect : Всякий c: [STEAM_1:0:2113616184] -> Reason : Забанен админом: Server
> Причина: "Banned by NoCheatZ 4 : aimbot"
