### ISSUE TITLE
Name spamm Bans 

### ISSUE THREAD

**Issue by BlackYuzia** [L-EARN/NoCheatZ-4#204]
One player get ban with NameChange Spamm.
When I test that func. I get ban If I change to many count names.

but He say: 
> Unban me

That the same player who say:

> Unban me, I not use aim, your AC is bad.

Why then I'm Laughing...
He say, change name only 3 times.
I research logs, but I not see anything triggers or others. 
Only reason and ban:
How many times can I change the nickname to get a ban.
What a delay should be that I would not get a ban.

You can add func: Time to other bans.
I mean: 
You can add other time to other reasons.

> example:
> ncz bantime namespamm 5
> ncs bantime aimbot 0
> ncs bantime autoattack 120
> etc

I think one time for all reasons. That not good

**Comment by hooliganxxx** [comment]
Just checking whether one of my bans is valid as weill - having a similar guy lol (but his KDR is 1.75 - pretty normal) 
The logs for his ban:

08/01/17 01:49:53 [ Server Tick #11613] РџСЊСЏРЅС‹Р№ Р—Р°СЏС† STEAM_1:0:756864631 : aimbot detected 
08/01/17 01:49:53 [ Server Tick #11613] v4-r61-0-g031687e 
08/01/17 01:49:53 [ Server Tick #11613] :::: MouseDetectInfo { 
:::::::: Previous Pitch Angle : 4.286038, 
:::::::: Current Pitch Angle : 4.244018 (Delta -0.042020), 
:::::::: Is Mouse Inverted ? : 0, 
:::::::: Mouse Delta Y : 1, 
:::::::: Previous Yaw Angle : -142.259262, 
:::::::: Current Yaw Angle : -144.360260 (Delta -2.100998), 
:::::::: Mouse Delta X : 49, 
:::::::: CMD Buttons : 0x208, 
::::}

And a question not related to this at all - is there a way to donate you? 
I really appreciate your work, and im sure that many more people as well - and I understand how difficult and boring that might be sometimes, so I want to send you donations evvery time in a while. 
If you could place some link somewhere would be great for me and those other people who want to support you, and for you as well.

**Comment by BlackYuzia** [comment]
@hooliganxxx 
I have nothing against. But I do not think that to mold everything into one theme is a good idea

**Comment by L-EARN** [comment]
@BlackYuzia SpamChangenameTester was supposed to ban only 10 minutes. But now this time is overriden by BanRequest SetBanTime.
I fix this by kicking instead of banning.

@hooliganxxx Consider this as false because there is only one detection and the faulting delta is very low. You should have posted in #198 also.
