### ISSUE TITLE
[REPORT] AllowWriteBans ComeBack is True

### ISSUE THREAD

**Issue by BlackYuzia** [L-EARN/NoCheatZ-4#206]
I decided to unsubscribe regarding: **AllowWriteBans**
If you have not checked or are not sure about its work.
I edit cvar:
> AllowWriteBans No
And now STEAMID and IP are not add in **banned_ip**.cfg and **banned_user**.cfg
I think now this work.

**Comment by L-EARN** [comment]
Thank you.

**Comment by hooliganxxx** [comment]
Hmm, I will report later, but yesterday I updated got he latest release, and today I found some people on those cfg files. Allowwritebans was set to No. However, these could be those from before yesterday. I will report later if I find more people in there.
