### ISSUE TITLE
ADMIN CHECKER OFF/ON 

### ISSUE THREAD

**Issue by BlackYuzia** [L-EARN/NoCheatZ-4#207]
Hi, @L-EARN 
You can add func to NCZ

> > ncz check admin on/off
> ncz check aimbot admin off/log/BAN_NOW/BAN_ASYNS 
> ncz check autoattack admin off/log/BAN_NOW/BAN_ASYNS  
> ncz check jumptester admin off/log/BAN_NOW/BAN_ASYNS 
> ncz check speedtester admin off/log/BAN_NOW/BAN_ASYNS  
> ncz check Cmds (all) admin off/log /BAN_NOW/BAN_ASYNS 
> ncz check bantime admin 10   // Set time for ban admin (in min)

Why that?
I want test all, and admin too.
I hope you help.
Of course, if it's not too difficult for you.

**Comment by L-EARN** [comment]
Hi,

I'm sorry. But as I mentionned in an earlier issue, I will never implement any sort of immunity for admins.
Your solutions are to implement it yourself or to disable kick/ban when you test the plugin.

Thank you.

**Comment by BlackYuzia** [comment]
@L-EARN you mean, Admins check too?
If YES - that good

**Comment by L-EARN** [comment]
All humans present on the server are tested. No immunity.

**Comment by BlackYuzia** [comment]
THAT GREAT

**Comment by BlackYuzia** [comment]
But, What a ID admins?

**Comment by L-EARN** [comment]
Admin IDs is only used to redirect chat-logs.

**Comment by BlackYuzia** [comment]
admin_ids=

**Comment by BlackYuzia** [comment]
and Where he is?

**Comment by BlackYuzia** [comment]
Where Redirect

**Comment by L-EARN** [comment]
If you want detection messages to be sent only for admins (admin_ids), use ncz Logger AllowChat admin.
If you want detection messages to be sent for all players, use ncz Logger AllowChat yes.
If you don't want at all to see detection messages, use ncz Logger AllowChat no.
