### ISSUE TITLE
ConVar request timed out on a good player again

### ISSUE THREAD

**Issue by hooliganxxx** [L-EARN/NoCheatZ-4#210]
Hi, again happened to a good player. 
R65, happened just now.

`08/02/17 10:56:21 [ Server Tick #158213] KOT9 STEAM_1:1:57915003 : sv_cheats ConVar request time out detected`
`08/02/17 10:56:21 [ Server Tick #158213] v4-r65-0-ga1ad598`
`08/02/17 10:56:21 [ Server Tick #158213] :::: CurrentConVarRequest {`
`:::::::: Request Status : SENT,`
`:::::::: Request Sent At : 46144.888448,`
`:::::::: Attempts : 6,`
`:::::::: ConVarInfo {`
`:::::::::::: ConVar Name : sv_cheats,`
`:::::::::::: Expected Value : 0,`
`:::::::::::: Got Value : NO ANSWER - TIMED OUT,`
`:::::::::::: Answer Status : NO STATUS,`
`:::::::::::: Comparison Rule : SAME_AS_SERVER`
`::::::::}`
`::::}`

The problem with this player is that he has poor internet connection as he lives outside the city, and shares it with his mobile data.
I'm strongly positive he isnt a hacker.

**Comment by L-EARN** [comment]
Don't make me sad : Is he the only one or some other players always get the same ?

**Comment by hooliganxxx** [comment]
He is the only one being banned for this exact reason.
The other ones have bypassers and stuff like that so i dont believe them beilng clean.
This one just timed out.

If you go to `http://csgo.cs-derzkiy.ru/index.php?p=banlist`
You can find him (currently 9th from top, unbanned)? copy paste the reason and put in search field above. He will be the only one. However if you type `sv_cheats ConVar` there would be much more ones.

You can use my banlist for statistic.
It's pretty good, considering that for a week the server was on I had more than total 5500 players
(you can see at `ranking.cs-derzkiy.ru`)

**Comment by L-EARN** [comment]
I'm not quite sure I can fix this.

His poor connection means he have loss of network packets.
But if I also clear players that have loss of network packets, cheaters will benefit from that.
And I will NEVER add an immunity option.

So what should I do ? Nothing. It's not my problem. Sorry. It's the problem of the client.
The only thing I can do is to tell admins that a loss can trigger false detections. That's all.

**Comment by hooliganxxx** [comment]
Thanks, I just reported that so you could know. He is only 1 person I can easily deal with that :)
