### ISSUE TITLE
Compat with gloves plugin

### ISSUE THREAD

**Issue by MazaHakers** [L-EARN/NoCheatZ-4#212]
You're not forced to complete all the followings, but any detail can help.

### Steps to reproduce the problem ?

Thank you.

**Comment by MazaHakers** [comment]
Hello, need a fix please for protection from the WH and the plug on the gloves, the fact that after the death of the player gloves hang in the air and across the map

**Comment by L-EARN** [comment]
Hi,

Thank you for reporting this issue.
But I do not get you you're trying to describe.

So please give me more informations.

A video would be great. With logs. Thank you.

**Comment by MazaHakers** [comment]
here is a screenshot http://i12.pixs.ru/storage/9/1/2/SnimokPNG_8910982_27071912.png of the link on which in the air hanging gloves, that is, after the player dies they should be removed, but the Creator of the plugin on the gloves said it is a bug from the protection of WH - conflict with this plugin

**Comment by MazaHakers** [comment]
![default](https://user-images.githubusercontent.com/30663647/28883727-16ea2930-77b8-11e7-915e-5b988a56cc7b.PNG)
conflict with this plugin

**Comment by L-EARN** [comment]
I'm so mad.

Where can I find this fu*** plugin code ?

**Comment by MazaHakers** [comment]
threw the theme Creator plugin for gloves as it is private I hope he will write here and you will solve this problem

**Comment by L-EARN** [comment]
This plugin seems illegal. I must not consider this issue until you can prove there is a real bug inside nocheatz, not affected by other plugins.

**Comment by MazaHakers** [comment]
I checked personally with your anti-cheat work without, the result is that without a working well, and with the anticheat a bug that has to do with illegal plug-in now each holder of servers use them, if you want to make your anti-cheat used by many projects that need time to resolve small issues of conflict
the response from the Creator of the plugin on the gloves https://forums.alliedmods.net/showthread.php?t=299977
tell included
sm_gloves_enable_world_model

**Comment by L-EARN** [comment]
I'm sorry. I don't need my anticheat used by many projects.
I need it to be fast, consistent, safe, configurable, easy to use and open-source.

Open-source.

So if it doesn't please you, just fork it and fix that yourself.

I will not deal with illegal things : I don't have time for this bullshit, I'm don't courageous anough to face legal issues and I DON'T FUCKING CARE YOU DON'T LOVE MY WORK, THAT IS DONE FOR FREE AND FOR YOU ALL.
I repeat : If you're not okay with this, just code your own anticheat.

 Thank you for your understanding.

Goodbye.
