### ISSUE TITLE
Assertion Fail CSGO - Windows

### ISSUE THREAD

**Issue by SM91337** [L-EARN/NoCheatZ-4#23]
Hello, I have compiled using Visual Studio 2015 and when I installed to my server i got the following error: http://puu.sh/piSu2/b2b9422521.png

Also after I connect to server (When I clicked ignore) it crashed and wrote a minidump:
http://puu.sh/piTrI/97e208b968.zip

It appears to be failing at line 240 then failing again at 245 which is the reason its Asserting 0.
http://puu.sh/piXKI/ddeb74c02e.png
http://puu.sh/piXXj/8bf26a7851.png
Any ideas?

Thanks

**Comment by L-EARN** [comment]
Hi,

This is from the new RadarHackBlocker system that is not yet ready for CS:GO.
I forgot to disable it ... hmm, sorry.

You can disable it in the `addons\NoCheatZ\config.ini` file, line 25: 

```
f_smoke_radius=110.0
disable_systems=ValidationTester;RadarHackBlocker
[CSTRIKE]
```

As you are building the project, you must also do it in the `server-plugin\Res\config.ini` file or it will get overwrited everytime you build.

Thanks for reporting this.

Related #16 @askovpen
