### ISSUE TITLE
[feature request] ban via sourcemod

### ISSUE THREAD

**Issue by askovpen** [L-EARN/NoCheatZ-4#29]
can plugin ban via command sm_ban or sm_addban?

**Comment by L-EARN** [comment]
Yes this is entirely possible.

I already did it with NoCheatZ 3 but as I completly re-wrote the plugin I did not implemented that yet in this version.

I must also add a note for myself : The ban message doesn't show up correctly because of the banip command.

**Comment by askovpen** [comment]
with sourcemod plugins i can manage bans via sql. (sourcebans)
