### ISSUE TITLE
AntiFlashbangBlocker does not account for m_flFlashMaxAlpha

### ISSUE THREAD

**Issue by SM91337** [L-EARN/NoCheatZ-4#37]
Hello, it appears when a player is partially flashed they will be blinded fully when using AntiFlashbangBlocker 

Preview here: http://plays.tv/video/576757b1753ed30654/anti-no-flash-bug

**Comment by L-EARN** [comment]
This module actually takes account for m_flFlashMaxAlpha and only process when m_flFlashMaxAlpha is maximum.

The error is the processing time. I will need to confirm this but you got flashed with a maximum alpha with a very short time and the plugin expended this time.

I will try with a different color and fix this.

**Comment by SM91337** [comment]
After turning away from the flash, It should of only partially blinded me, although it made the screen full white, I will post a video demonstrating normal behavior.

**Comment by SM91337** [comment]
Another thing you could do is send m_iHideHUD with the flags 1<<2 while the player is blind, this should make the new flash event more realistic.

In sourcemod you would do:
SetEntProp(iClient, Prop_Send, "m_iHideHUD", 1<<2); although I am not sure about C++

**Comment by L-EARN** [comment]
Fixed in d7330b3
