### ISSUE TITLE
Infinite GOTV bot loop

### ISSUE THREAD

**Issue by SM91337** [L-EARN/NoCheatZ-4#39]
When the server is empty it will restart / change map in an infinite loop in attempt to spawn the GOTV bot.

**Comment by L-EARN** [comment]
Hi,

The tv_enable 1 must be followed by a changelevel to spawn the GOTV but some server sellers do not allow GOTV and this leads to the infinite loop you have (Any other issue that makes the GOTV unable to connect will do this though).

So I'll fix this by changing the level once ... and if no GOTV it doesn't really matter ...

Thanks for reporting this.

related #16 
related #30

**Comment by SM91337** [comment]
Just a note, when I join the server its fine, but an empty server appears to have the issue.

**Comment by L-EARN** [comment]
Yes this is also another thing.

With CS:S, the server does game frames even when hibernating. So the plugin can run timers and reload the map in time.
With CS:GO, it doesn't run game frames when hibernating. So the changelevel is done once the first client connects.

I did not tested the behavior with sv_hibernate_when_empty 0.

**Comment by SM91337** [comment]
Might be an idea to check the player count before attempting to spawn bot.

**Comment by L-EARN** [comment]
This would be embarassing to change the level when you have players ready in your server ...

**Comment by SM91337** [comment]
You could probably force the cvar to enabled while the server is empty and I believe when the server finishes hibernating (ie: a player joins)  he GOTV bot should automatically be spawned and ready. While a server is in hibernation any type of bot will wait for the first player to join before it spawns itself in order to save resources, this can be disabled using v_hibernate_when_empty 0 although I don't see this as being an ideal workaround.
