### ISSUE TITLE
[Suggestion] Teleport / Crash fix?

### ISSUE THREAD

**Issue by SM91337** [L-EARN/NoCheatZ-4#62]
Regarding #8 (Teleport cheats) it appears it is possible for the player to crash the server as seen here: https://www.youtube.com/watch?v=2vkLKLOhbxQ

The fix seems to be possible in 2 ways:

Prevent player from sending malformed usercmds: https://forums.alliedmods.net/showpost.php?p=2431788&postcount=51

Or fix the eye angles: https://forums.alliedmods.net/showpost.php?p=2429410&postcount=16 (This might lag though not sure)

Maybe you can implement one or both of these fixes (Just a suggestion)

**Comment by L-EARN** [comment]
Hi,

Normalizing angles would prevent another tester to work.
However checking the range of floating point values as in the first solution inside the command is not a bad idea, if this really is the root cause of the hack.
