### ISSUE TITLE
sm_ban not work

### ISSUE THREAD

**Issue by askovpen** [L-EARN/NoCheatZ-4#64]
```
07/10/16 18:04:10 [ Server Tick #6559, SourceTV:NoCheatZ-autorecords/de_dust2x2_classic-07-10-16_18-02-39.dem : Tick #578
7 ] Banned k1ng of the bongo [STEAM_1:0:89364799 - 178.91.118.121:27005] with reason : Banned by NoCheatZ 4
```
source mod banlist empty and server banlist empty.

**Comment by L-EARN** [comment]
Hi,

I will try to trigger a ban on myself and see if this works with and without SM ... when I will have time, soon.

Can you provide me the detection or the system that triggered this ban please ?

**Comment by L-EARN** [comment]
Related #84 : sm_ban still not working. Need investigations.
