### ISSUE TITLE
Ability to remove select convars from ConVarTester

### ISSUE THREAD

**Issue by rsgua** [L-EARN/NoCheatZ-4#76]
How to disable this check?
07/27/2016 08:07:37 PM [ Server Tick #19167] ConVarTester triggered a detection : [STEAM_1:1:1 - ] is using a mp_forcecamera ConVar Bypasser.
07/27/2016 08:07:37 PM [ Server Tick #19167] :::: CurrentConVarRequest {
:::::::: Request Status : REPLYED,
:::::::: Request Sent At : 169.116211,
:::::::: ConVarInfo {
:::::::::::: ConVar Name : mp_forcecamera,
:::::::::::: Expected Value : 1,
:::::::::::: Got Value : 0,
:::::::::::: Answer Status : ValueIntact,
:::::::::::: Comparison Rule : SAME_AS_SERVER
::::::::}
::::}

**Comment by L-EARN** [comment]
Hi,

There is currently no way to disable one select convar in ConVarTester.

But you can disable the entire ConVarTester.

Can you tell me the plugin that is changing this convar please ?

**Comment by rsgua** [comment]
https://forums.alliedmods.net/showthread.php?t=182412&page=19
