### ISSUE TITLE
Bunny Hop detection not work correctly

### ISSUE THREAD

**Issue by rsgua** [L-EARN/NoCheatZ-4#77]
Bunny Hop detection not work correctly. Too many ban for this.

**Comment by L-EARN** [comment]
The plugin must kick users of bunny hop scripts and ban users of bunny hop programs interacting with the game memory.

If you get banned without scripts or program, but only because you used your keyboard so this is not the correct behavior of the plugin.

Please confirm the behavior is correct or not.

**Comment by rsgua** [comment]
plugin ban players without bunny hop.

**Comment by L-EARN** [comment]
This isn't explicit enough ...

Please, answer those questions : 

- Do you have a T**V record that shows the false detection(s)** in action ?
- Players **were jumping or not** when detection(s) triggered ?
- Are you using **another server-plugin that makes all players bunny-hopping** ?

And for any answer, **please additionally give me the log output**, if any. 
If there is no such output in logs, please tell me there is no output in logs but players are still banned by NoCheatZ 4.

In the meantime, _ and if you don't want to help me find the issue_, you can disable the JumpTester.

**Comment by L-EARN** [comment]
Did the players used the jump key on mousewheel or not ?

**Comment by blackhawk74** [comment]
Can also confirm that this is an issue. Within 30 seconds of joining, using scroll wheel to jump I got kicked.

Log file attached.
[NoCheatZ-17-Sep-2016.txt](https://github.com/L-EARN/NoCheatZ-4/files/478460/NoCheatZ-17-Sep-2016.txt)

Demo: https://drive.google.com/open?id=0B0IJtbqhEr_JWURaNnlrYXRfZVk

**Comment by L-EARN** [comment]
Ok thanks for confirming so "it works".

It's just a problem of understanding. Using the jump key on scroll is similar as using a script. That's my point of view. It's a little game modification that makes you able to bunny.

The good point is on this detection, the plugin made the difference and was able to tell it was only a script, not a program.

So maybe it's possible to have an option to remove script detection only and keep program detection.

What do you think about that ?

**Comment by blackhawk74** [comment]
I can agree with that. A large portion of higher level players (at least in CS) have scroll wheel (either mwheelup and/or mwheeldown) bound to +jump, it is extremely common. Now, if detection was based on intervals between +jump (see [Macrodox](https://forums.alliedmods.net/showthread.php?p=1678026) for example), and if those intervals were exact, unlike using a scroll wheel, that would make sense to kick/ban.
