### ISSUE TITLE
Not work aimbot detection and other

### ISSUE THREAD

**Issue by rsgua** [L-EARN/NoCheatZ-4#78]
I tested aimware and midnight cheat and anticheat now work. Not ban my for wh, trigger bot function.
Recoil + Trigger bot detection (midnight cheat): 
07/28/2016 02:59:16 PM [ Server Tick #143702, SourceTV:NoCheatZ-autorecords/de_dust2-07-28-2016_02-40-47 PM.dem : Tick #141973 ] ShotTester triggered a detection : RSG [STEAM_1:1:170751407 - 46.63.34.220:27005] is using a AutoPistol.
07/28/2016 02:59:16 PM [ Server Tick #143702, SourceTV:NoCheatZ-autorecords/de_dust2-07-28-2016_02-40-47 PM.dem : Tick #141973 ] :::: ShotStatsT {
:::::::: Attack1 Button Up At (Time) : 1140.116821,
:::::::: Attack1 Button Down At (Time) : 1140.086914,
:::::::: Clicks {
:::::::::::: Clicks Count : 72,
:::::::::::: Detection Ratio : 101.408447,
:::::::::::: Average Button Down Hold Time : 0.207014 s
:::::::: },
:::::::: ShortClicks {
:::::::::::: Clicks Count : 37,
:::::::::::: Detection Ratio : 52.857143,
:::::::::::: Average Button Down Hold Time : 0.101257 s
:::::::: },
:::::::: WithHand {
:::::::::::: Clicks Count : 0,
:::::::::::: Detection Ratio : 0.000000,
:::::::::::: Average Button Down Hold Time : 0.000000 s
:::::::: },
:::::::: WithPistol {
:::::::::::: Clicks Count : 20,
:::::::::::: Detection Ratio : 28.571428,
:::::::::::: Average Button Down Hold Time : 0.080907 s
:::::::: },
:::::::: WithAuto {
:::::::::::: Clicks Count : 17,
:::::::::::: Detection Ratio : 60.714287,
:::::::::::: Average Button Down Hold Time : 0.080977 s
:::::::: },
:::::::: OnTarget {
:::::::::::: Clicks Count : 0,
:::::::::::: Detection Ratio : 0.000000,
:::::::::::: Average Button Down Hold Time : 0.000000 s
:::::::: },
:::::::: Consecutive Detections Count : 11,
:::::::: Last Detection Time : 1139.945190
:::: }

**Comment by rsgua** [comment]
Trigger bot detection:
07/28/2016 03:26:40 PM [ Server Tick #71111, SourceTV:NoCheatZ-autorecords/de_dust2-07-28-2016_03-17-36 PM.dem : Tick #69577 ] ShotTester triggered a detection : RSG [STEAM_1:1:170751407 - 46.63.34.220:27005] is using a AutoPistol.
07/28/2016 03:26:40 PM [ Server Tick #71111, SourceTV:NoCheatZ-autorecords/de_dust2-07-28-2016_03-17-36 PM.dem : Tick #69577 ] :::: ShotStatsT {
:::::::: Attack1 Button Up At (Time) : 2783.621094,
:::::::: Attack1 Button Down At (Time) : 2783.597168,
:::::::: Clicks {
:::::::::::: Clicks Count : 51,
:::::::::::: Detection Ratio : 102.000000,
:::::::::::: Average Button Down Hold Time : 0.132357 s
:::::::: },
:::::::: ShortClicks {
:::::::::::: Clicks Count : 36,
:::::::::::: Detection Ratio : 72.000000,
:::::::::::: Average Button Down Hold Time : 0.091972 s
:::::::: },
:::::::: WithHand {
:::::::::::: Clicks Count : 0,
:::::::::::: Detection Ratio : 0.000000,
:::::::::::: Average Button Down Hold Time : 0.000000 s
:::::::: },
:::::::: WithPistol {
:::::::::::: Clicks Count : 0,
:::::::::::: Detection Ratio : 0.000000,
:::::::::::: Average Button Down Hold Time : 0.000000 s
:::::::: },
:::::::: WithAuto {
:::::::::::: Clicks Count : 36,
:::::::::::: Detection Ratio : 72.000000,
:::::::::::: Average Button Down Hold Time : 0.091901 s
:::::::: },
:::::::: OnTarget {
:::::::::::: Clicks Count : 0,
:::::::::::: Detection Ratio : 0.000000,
:::::::::::: Average Button Down Hold Time : 0.000000 s
:::::::: },
:::::::: Consecutive Detections Count : 20,
:::::::: Last Detection Time : 2783.620850
:::: }

**Comment by L-EARN** [comment]
Hi,

I don't understand what is the issue.

Some cheats can't be detected by the current systems of the plugin, depending of the settings the cheat is using.

What is the issue ?
