### ISSUE TITLE
False No recoil

### ISSUE THREAD

**Issue by AJIekceu4** [L-EARN/NoCheatZ-4#79]
Hello. Today i was trying to test AC with my friend on my own server and get false detection:

> 08/15/2016 03:11:38 PM [ Server Tick #33149, SourceTV:NoCheatZ-autorecords/de_dust2-08-15-2016_03-07-32 PM.dem : Tick #31524 ] EyeAnglesTester triggered a detection : RoboSapien [STEAM_1:1:21423132 - *********:27005] is using a No recoil.
08/15/2016 03:11:38 PM [ Server Tick #33149, SourceTV:NoCheatZ-autorecords/de_dust2-08-15-2016_03-07-32 PM.dem : Tick #31524 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 1.211929,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : -67.925629,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000059,
:::::::::::: Detections Count : 1d
:::::::: }
:::: }
> 

STEAM_1:1:21423132 - it is i am. And i did not use any scripts or cheats $)

This is demo file and i don't see any strange action from my side:
www.csgo.org/files/de_dust2-08-15-2016_03-07-32.7z

**Comment by L-EARN** [comment]
Hi,

For some reasons the Z axis is not zero and this should not happen when we play.

Maybe this is related to the latest update of CSGO that remove loss of precision in angles networking, but precision errors can be added by angles calculations in the game.

**Comment by L-EARN** [comment]
This is really not normal.

You were dead when the detection happened. But EyeAnglesTester is not supposed to process dead players.

**Comment by AJIekceu4** [comment]
May be it is because after my dead, i start to play alive bot?

**Comment by L-EARN** [comment]
I found that in the case you spawn but get dead less than 3 seconds after your spawn then you enter in tests even if you are dead.
So this issue is just about a bad timer reset.

As for taking control of a bot, I must look into it because I think it can prevent some testers to work, including the EyeAnglesTester.
I did not implemented anything for this feature yet because I forgot about that.
