### ISSUE TITLE
Reply to this - I make YOUR anti cheat for free

### ISSUE THREAD

**Issue by L-EARN** [L-EARN/NoCheatZ-4#8]
I have a roadmap for this project.

I'm not always doing things here, sometimes I can last 9 months without touching anything just because it makes me mad and I prefer to switch in my other passion ... and sometimes like right now I'm in the rush to make it the top anticheat for Source Engine.

So if you have any cheating or hacking problems with your server you can tell me right here, in this issue, what you want.

I will add it to my roadmap.

Current roadmap (by priority) : 

* Fix current issues
* Make it working for CSGO
* Test detection consistency for CS:S and CS:GO
* Block FarESP for CS:S
* Make FarESP blocking work for CSGO
* XML output of detections and logs, sorted by SteamIDs, TIme and even SourceTV record filename.
* Kick or fix bad player cmd rates
* Fix Source Engine hacks (ServerProtect system)
* Test detection consistency for CS:S and CS:GO
* AntiRconPasswordDisclosure (ServerProtect system)
* AntiAbsolutePathDisclosure (ServerProtect system) [Require hook of network traffic]
* Test detection consistency for CS:S and CS:GO
* External program to view the graph of players CUserCmds
* (Will probably not do this because this will kill your server) Predict aimbots behaviors

**Comment by SM91337** [comment]
We sometimes get teleport hackers, Its part of a cheat called aimware, maybe you can make teleport detection? Also if it possible could you add a Wallhack / ESP scrambler? Which sends fake client location data to confuse cheaters? I believe I saw such feature a very long time ago in a CS 1.6 anticheat but I can't remember.

**Comment by L-EARN** [comment]
Hi,

While Wallhacks are already blocked in NoCheatZ 4, it's also already planned to block ESP and radarhacks by sending fake informations.

The Gold Source Engine is very different of Source Engine about transmitting data to clients but it's still possible to find solutions.
The SourceMod Anti-Cheat already integrated this a while ago, I will try to go further (even a little bit) as I did with the anti smoke blocker.

For the teleport thing, I'm surprised this is not already fixed ... I will investigate on this one day (First I will have to make a helper system to dump the data sent by clients in realtime)

**Comment by SystematicMania** [comment]
I've always wanted to do this, but I never got around to it. If you can send different netprop values to different players, then it's possible to eliminate the remaining advantages of ESP (seeing money, remaining ammo, health, etc), break certain aimbots, and deal wallhacks a fatal blow (similarly to FarESP).

[Afronanny tried it a while ago](https://forums.alliedmods.net/showpost.php?p=1581439&postcount=29), but he ran into obstacles. The system requirements can be reduced by populating a CFrameSnapshot per team (spec, ts, cts) rather than per player.

**Comment by L-EARN** [comment]
@SystematicMania : 

Hi,

Currently this plugin doesn't send different netprop values to different players.
netprops values are not modifyed excepted for the radar informations on CS:S.

However I looked in the engine source sdk from 2007, it seems like it is possible to tweak the netprop values and send fake informations for some select players : 
- On pre CBaseServer::WriteDeltaEntities : 
* Convert CBaseClient to edict (So we know who will receive the update)
* Save current netprops we will modify somewhere
* Modify netprops of other clients to something odd.

The engine will now create a network update message to this client by copying values using a pointer to the the corresponding ServerClass of the entities it sends (For both FullUpdates and DeltaUpdates)

- On post CBaseServer::WriteDeltaEntities
* Reset back the normal netprops.
* Wait for another client to be processed ...

Sorry if I'm not clear ...

But I think this could work, if this is the same implementation in the current engines.

Related sources : 
https://github.com/LestaD/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/engine/sv_client.cpp
https://github.com/LestaD/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/engine/baseclient.cpp
https://github.com/LestaD/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/engine/sv_framesnapshot.cpp
https://github.com/LestaD/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/engine/sv_ents_write.cpp
