### ISSUE TITLE
False AutoPistol

### ISSUE THREAD

**Issue by AJIekceu4** [L-EARN/NoCheatZ-4#80]
> 08/15/2016 05:03:39 PM [ Server Tick #20107, SourceTV:NoCheatZ-autorecords/de_dust2-08-15-2016_05-01-20 PM.dem : Tick #17776 ] ShotTester triggered a detection : BlackDogvkcsgo.ru [STEAM_1:1:97460027 -            :27005] is using a AutoPistol.
08/15/2016 05:03:39 PM [ Server Tick #20107, SourceTV:NoCheatZ-autorecords/de_dust2-08-15-2016_05-01-20 PM.dem : Tick #17776 ] :::: ShotStatsT {
:::::::: Attack1 Button Up At (Time) : 3291.723389,
:::::::: Attack1 Button Down At (Time) : 3291.700195,
:::::::: Clicks {
:::::::::::: Clicks Count : 51,
:::::::::::: Detection Ratio : 102.000000,
:::::::::::: Average Button Down Hold Time : 0.120094 s
:::::::: },
:::::::: ShortClicks {
:::::::::::: Clicks Count : 39,
:::::::::::: Detection Ratio : 78.000000,
:::::::::::: Average Button Down Hold Time : 0.078004 s
:::::::: },
:::::::: WithHand {
:::::::::::: Clicks Count : 0,
:::::::::::: Detection Ratio : 0.000000,
:::::::::::: Average Button Down Hold Time : 0.000000 s
:::::::: },
:::::::: WithPistol {
:::::::::::: Clicks Count : 39,
:::::::::::: Detection Ratio : 78.000000,
:::::::::::: Average Button Down Hold Time : 0.078004 s
:::::::: },
:::::::: WithAuto {
:::::::::::: Clicks Count : 0,
:::::::::::: Detection Ratio : 0.000000,
:::::::::::: Average Button Down Hold Time : 0.000000 s
:::::::: },
:::::::: OnTarget {
:::::::::::: Clicks Count : 0,
:::::::::::: Detection Ratio : 0.000000,
:::::::::::: Average Button Down Hold Time : 0.000000 s
:::::::: },
:::::::: Consecutive Detections Count : 19,
:::::::: Last Detection Time : 3291.707520
:::: }
08/15/2016 05:03:39 PM [ Server Tick #20107, SourceTV:NoCheatZ-autorecords/de_dust2-08-15-2016_05-01-20 PM.dem : Tick #17776 ] Banned BlackDogvkcsgo.ru [STEAM_1:1:97460027 -  :27005] with reason : Banned by NoCheatZ 4

> 08/15/2016 05:20:44 PM [ Server Tick #151280, SourceTV:NoCheatZ-autorecords/de_dust2-08-15-2016_05-01-20 PM.dem : Tick #148949 ] ShotTester triggered a detection : PAYET [STEAM_1:1:105103638 - 59017] is using a AutoPistol.
08/15/2016 05:20:44 PM [ Server Tick #151280, SourceTV:NoCheatZ-autorecords/de_dust2-08-15-2016_05-01-20 PM.dem : Tick #148949 ] :::: ShotStatsT {
:::::::: Attack1 Button Up At (Time) : 4316.512207,
:::::::: Attack1 Button Down At (Time) : 4316.473633,
:::::::: Clicks {
:::::::::::: Clicks Count : 53,
:::::::::::: Detection Ratio : 101.923080,
:::::::::::: Average Button Down Hold Time : 4.251497 s
:::::::: },
:::::::: ShortClicks {
:::::::::::: Clicks Count : 21,
:::::::::::: Detection Ratio : 40.384617,
:::::::::::: Average Button Down Hold Time : 0.091246 s
:::::::: },
:::::::: WithHand {
:::::::::::: Clicks Count : 0,
:::::::::::: Detection Ratio : 0.000000,
:::::::::::: Average Button Down Hold Time : 0.000000 s
:::::::: },
:::::::: WithPistol {
:::::::::::: Clicks Count : 21,
:::::::::::: Detection Ratio : 40.384617,
:::::::::::: Average Button Down Hold Time : 0.091246 s
:::::::: },
:::::::: WithAuto {
:::::::::::: Clicks Count : 0,
:::::::::::: Detection Ratio : 0.000000,
:::::::::::: Average Button Down Hold Time : 0.000000 s
:::::::: },
:::::::: OnTarget {
:::::::::::: Clicks Count : 0,
:::::::::::: Detection Ratio : 0.000000,
:::::::::::: Average Button Down Hold Time : 0.000000 s
:::::::: },
:::::::: Consecutive Detections Count : 21,
:::::::: Last Detection Time : 4316.512207
:::: }
08/15/2016 05:20:44 PM [ Server Tick #151280, SourceTV:NoCheatZ-autorecords/de_dust2-08-15-2016_05-01-20 PM.dem : Tick #148949 ] Banned PAYET [STEAM_1:1:105103638 -  :59017] with reason : Banned by NoCheatZ 4

This is full demo from autodemo plugin (ncz AutoTVRecord disable)
http://www.csgo.org/files/17-01_17-26_de_dust2.zip

On these demo i did not see any strange actions from this 2 banned players. May be this bans can be  related with network issue on server side? Today in datacenter where i host my server some problems and every 10 minutes network is down (for 5-10 sec).

**Comment by L-EARN** [comment]
Hi,

The detections seems good.

I will look at the demo anyway one day.

**Comment by AJIekceu4** [comment]
> The detections seems good.

OK, how can i disable banning players (only logging to console or file) to check all players? I have csgo server with good online and can test AC, but don't see how can i turn off banning.

**Comment by L-EARN** [comment]
There is currently no way to disable bans or kicks.

**Comment by musosoft** [comment]
same issue on CS:S, one legit player got banned:

```
09/26/2016 03:15:01 PM [ Server Tick #2313, SourceTV:NoCheatZ-autorecords/de_nightfever-09-26-2016_03-14-37 PM.dem : Tick #1571 ] ShotTester triggered a detection : OnlineHero [[U:1:41485353] - 212.96.189.251:64497] is using a AutoPistol.
09/26/2016 03:15:01 PM [ Server Tick #2313, SourceTV:NoCheatZ-autorecords/de_nightfever-09-26-2016_03-14-37 PM.dem : Tick #1571 ] :::: ShotStatsT {
:::::::: Attack1 Button Up At (Time) : 4372.167480,
:::::::: Attack1 Button Down At (Time) : 4372.137207,
:::::::: Clicks {
:::::::::::: Clicks Count : 53,
:::::::::::: Detection Ratio : 101.923080,
:::::::::::: Average Button Down Hold Time : 0.161926 s
:::::::: },
:::::::: ShortClicks {
:::::::::::: Clicks Count : 28,
:::::::::::: Detection Ratio : 56.000000,
:::::::::::: Average Button Down Hold Time : 0.105201 s
:::::::: },
:::::::: WithHand {
:::::::::::: Clicks Count : 0,
:::::::::::: Detection Ratio : 0.000000,
:::::::::::: Average Button Down Hold Time : 0.000000 s
:::::::: },
:::::::: WithPistol {
:::::::::::: Clicks Count : 28,
:::::::::::: Detection Ratio : 56.000000,
:::::::::::: Average Button Down Hold Time : 0.105401 s
:::::::: },
:::::::: WithAuto {
:::::::::::: Clicks Count : 0,
:::::::::::: Detection Ratio : 0.000000,
:::::::::::: Average Button Down Hold Time : 0.000000 s
:::::::: },
:::::::: OnTarget {
:::::::::::: Clicks Count : 0,
:::::::::::: Detection Ratio : 0.000000,
:::::::::::: Average Button Down Hold Time : 0.000000 s
:::::::: },
:::::::: Consecutive Detections Count : 22,
:::::::: Last Detection Time : 4371.942871
:::: }
09/26/2016 03:15:01 PM [ Server Tick #2313, SourceTV:NoCheatZ-autorecords/de_nightfever-09-26-2016_03-14-37 PM.dem : Tick #1571 ] Banned OnlineHero [[U:1:41485353] - 212.96.189.251:64497] with reason : Banned by NoCheatZ 4
```

**Comment by L-EARN** [comment]
The detection seems false indeed, as the other one on this issue. I don't know why I said it was good.
