### ISSUE TITLE
Error reading commandline string, not stripping eventual quotes

### ISSUE THREAD

**Issue by Weeeishy** [L-EARN/NoCheatZ-4#83]
Hello,

So I recently found this anti-cheat from AM and I have few questions. So if I want to install it, I have to simply drop the Release files to my servers right? Also, does it conflict with SMAC? If not, is it more efficient that SMAC? Do the bans showup in SourceBans? I know that might stupid but please bear with me :(.

Thank you!

**Comment by L-EARN** [comment]
To install it, you just have to merge the directories addons, cfg and others in the csgo directory of the server.

There is compatibility issues with SMAC : 
https://github.com/L-EARN/NoCheatZ-4/issues/63

SMAC has more functionnality now because it's a finished project, but it lacks supports of recent game changes because it's old and is a little slower.

Integration with sourcebans have been done but it needs to be tested further. Some bans might not show up when the server has not yet given userid to player.

**Comment by Weeeishy** [comment]
Awesome! I will install it in one of my retakes servers and hopefully I can test it and hunt bugs.

**Comment by Weeeishy** [comment]
Hi,

So I've compiled it using Visual Studio 2015 and copied the debug files to my game server which was already made, I've restarted it and it seems like  its not working for me. I tried ncz in the rcon but it showed me unknown command. How do I verify if it's working?

Thanks

**Comment by L-EARN** [comment]
Maybe the plugin failed to load because the config.ini file was not copied along with the binaries.
When you compile with vs, a script is launched to make a directory you just have to copy the content of it but you must copy the entire content of it.

If you can post the output of console in case you copyed everything I will be able to help you more.

**Comment by Weeeishy** [comment]
I've copied all of the addons and other files including the config.ini, but it appears that it's not loading. 

Here are the logs from the console.

http://pastebin.com/BcB1Y1v1

**Comment by L-EARN** [comment]
It's loading fine for me.

I suspect you put all the stuff in the wrong directory. Please confirm nocheatzX.dll is located according to the content of nocheatz.vdf

What is the windows version your server is running ?

**Comment by Weeeishy** [comment]
Huh,  the .dll file is located in csgo/addons/NoCheatZ and as far as I remember nocheatz.vdf was in the addons folder. Also Im on Windows server 2012.

**Comment by L-EARN** [comment]
Are you able to take a screenshot of the console rather than copying the output ?

Are you able to test with Windows Server 2012 R2 ?

**Comment by Weeeishy** [comment]
It's kinda hard to get a screenshot after I run the SRCDS cause the logs will move really fast. Yes, I'll be able to test on WS 2012 R2.

**Comment by Weeeishy** [comment]
Hi,

So I've tried your latest version (pre-compiled) and the server is crashing instantly.

I found this in the console.txt

```
[NoCheatZ v4-beta-r3-patch2-debug] 0.000000 Loading ...
[NoCheatZ v4-beta-r3-patch2-debug] 0.001000 [NoCheatZ v4-beta-r3-patch2-debug] Can't write to logfile at "csgo"/logs/NoCheatZ_4_Logs/NoCheatZ-25-Oct-2016.log ... Please check write access and if the directory exists.

[NoCheatZ v4-beta-r3-patch2-debug] 0.001000 ERROR : ConfigManager::LoadConfig : Cannot open config.ini
[NoCheatZ v4-beta-r3-patch2-debug] 0.002000 [NoCheatZ v4-beta-r3-patch2-debug] Can't write to logfile at "csgo"/logs/NoCheatZ_4_Logs/NoCheatZ-25-Oct-2016.log ... Please check write access and if the directory exists.

[NoCheatZ v4-beta-r3-patch2-debug] 0.002000 ERROR : ConfigManager::LoadConfig failed
Failed to load plugin "addons/NoCheatZ/nocheatzX"
```

This is my config.ini
```
[CONFIG]
config_version=1
[CSGO]
getdatadescmap_windows=11
getdatadescmap_linux=12
settransmit_windows=22
settransmit_linux=23
mhgroundentity_windows=175
mhgroundentity_linux=177
weaponequip_windows=281
weaponequip_linux=282
weapondrop_windows=283
weapondrop_linux=284
playerruncommand_windows=468
playerruncommand_linux=469
dispatch_windows=14
dispatch_linux=15
thinkpost_windows=51
thinkpost_linux=52
playerdataclass=CCSPlayer
f_smoketime=15.5
f_smoke_time_to_bang=0.75
f_inner_smoke_radius_sqr=5200.0
f_smoke_radius=110.0
disable_systems=ValidationTester;BadUserCmdBlocker;AutoTVRecord
[CSTRIKE]
getdatadescmap_windows=11
getdatadescmap_linux=12
settransmit_windows=20
settransmit_linux=21
mhgroundentity_windows=177
mhgroundentity_linux=179
weaponequip_windows=261
weaponequip_linux=262
weapondrop_windows=263
weapondrop_linux=264
playerruncommand_windows=419
playerruncommand_linux=420
dispatch_windows=12
dispatch_linux=13
thinkpost_windows=47
thinkpost_linux=48
playerdataclass=CCSPlayer
f_smoketime=15.5
f_smoke_time_to_bang=0.75
f_inner_smoke_radius_sqr=5200.0
f_smoke_radius=110.0
disable_systems=ValidationTester;BadUserCmdBlocker
```

OS: Windows Server 2012 R2, and it's Retakes server.

Wondering what could be the issue here. :/

**Comment by L-EARN** [comment]
Hi,

This is an error in both your start-script and in the plugin.

As you can see the plugin is looking for `"csgo"` directory, but it doesn't exists. The directory is `csgo`, not `"csgo"`.

And why ?
* In your start-script, you wrote `csgo.exe -console -game "csgo"`. But the plugin expect it to be written `csgo.exe -console -game csgo` 
* The plugin is not stripping eventual quotes here.
* It is needed for the plugin to look at the `game` value in the commandline string to detect the game before loading any server interface.

**Comment by Weeeishy** [comment]
Hello,

Unfortunately, I'm using Sedirector and these start up scripts are hard-coded and cannot be edited (-game and csgo.exe)

https://ashersoftware.com/seDirector/


Is there work around for that issue? Also, I'm sorry for the late reply.

**Comment by L-EARN** [comment]
There is no workaround ... yet.
