### ISSUE TITLE
EyeAnglesTester : too many bans

### ISSUE THREAD

**Issue by rodgerland** [L-EARN/NoCheatZ-4#84]
Be sure to install steamcmd to compile in Linux?
Folders with csgo steamcmd and in different ways.
The git cloned, established libraries, updated, compiled and set to release the game csgo.
All right?
Log error - "ERROR: CNoCheatZPlugin :: ClientCommand (pEntity: 0xedf5f040 -> pEntity-> classname: player -> clientname :, args: spectate): Invalid SlotStatus, can not process
"
What kind of mistake?
EyeAnglesTester seems not working, too many bans.

sm_ban works badly, 20 bans only one hit sm_ban

**Comment by L-EARN** [comment]
Steamcmd is not required to compile either for linux or Windows. But as I run a local server to test builds this is what I recommend to do.

The log error is just about the CSGO TV when it connects -> nothing really important right now except the command tester must also analyse commands issued by unknown entities (Just in case a bug allows this) but now this is just ignored by the plugin.

EyeAnglesTester should be running fine as long as you don't have any plugin that changes view angles while players are in game. Please be sure you don't have such plugins (Plugins spawning beams can trigger this also because of collisions). I will test it myself soon again just to be sure but it should be fine. If you have any evidence please feel free to upload.

For the sm_ban issue I will investigate more. Did you see any error related to sm_bans in nocheatz logs or sourcemod logs ? Please upload this also.

Thanks.

**Comment by rodgerland** [comment]
No errors in the logs.
Here are my plugins:
[SM] Listing 31 plugins:
  01 "Basic Comm Control" (1.7.2) by AlliedModders LLC
  02 "Fun Votes" (1.7.2) by AlliedModders LLC
  03 "AFK Ping Control" (1.3) by wS (World-Source.Ru)
  04 "Admin all spec" (1.0.2) by Dr! Fter
  05 "CS: GO Admin ESP" (2.1) by Root
  06 "Nextmap" (1.7.2) by AlliedModders LLC
  07 "Basic Commands" (1.7.2) by AlliedModders LLC
  08 "Admin File Reader" (1.7.2) by AlliedModders LLC
  09 "Reserved Slots" (1.7.2) by AlliedModders LLC
  10 "Client Preferences" (1.7.2) by AlliedModders LLC
  11 "Rock The Vote" (1.7.2) by AlliedModders LLC
  12 "SourceMod Anti-Cheat" (0.8.6.0) by SMAC Development Team
  13 "MapChooser" (1.7.2) by AlliedModders LLC
  14 "SourceComms" ((SB ++) 1.5.4.6) by Alex, Sarabveer (VEER ™)
  15 "Fun Commands" (1.7.2) by AlliedModders LLC
  16 "Sound Commands" (1.7.2) by AlliedModders LLC
  17 "Anti-Flood" (1.7.2) by AlliedModders LLC
  18 "SourceBans: Admin Config Loader" ((SB ++) 1.5.4.6) by AlliedModders LLC, Sarabveer (VEER ™)
  19 "SMAC Rcon Locker" (0.8.6.0) by SMAC Development Team
  20 "SourceBans ++" (1.5.4.6) by SourceBans Development Team, Sarabveer (VEER ™)
  21 "SMAC ConVar Checker" (0.8.6.0) by SMAC Development Team
  22 "SMAC Command Monitor" (0.8.6.0) by SMAC Development Team
  23 "Player Commands" (1.7.2) by AlliedModders LLC
  24 "Basic Chat" (1.7.2) by AlliedModders LLC
  25 "SMAC Client Protection" (0.8.6.0) by SMAC Development Team
  26 "Admin Help" (1.7.2) by AlliedModders LLC
  27 "Admin Menu" (1.7.2) by AlliedModders LLC
  28 "RandomCycle" (1.7.2) by AlliedModders LLC
  29 "Basic Info Triggers" (1.7.2) by AlliedModders LLC
  30 "Basic Votes" (1.7.2) by AlliedModders LLC
  31 "Custom Player Skins (Core)" (1.2.0) by Mitchell, Root

Maybe "Admin all spec" "CS: GO Admin ESP" interfere?
I'll try without them.

**Comment by musosoft** [comment]
The same issue here, legit players got ban:

```
09/26/2016 02:20:38 PM [ Server Tick #25206, SourceTV:NoCheatZ-autorecords/aim_deagle7k-09-26-2016_02-18-56 PM.dem : Tick #6814 ] EyeAnglesTester triggered a detection : Ĉע₡ϋ [[U:1:53656984] - 91.193.53.55:27005] is using a No recoil.
09/26/2016 02:20:38 PM [ Server Tick #25206, SourceTV:NoCheatZ-autorecords/aim_deagle7k-09-26-2016_02-18-56 PM.dem : Tick #6814 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : -16.453583,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : -94.010941,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : -0.000225,
:::::::::::: Detections Count : 1d
:::::::: }
:::: }

09/26/2016 03:21:24 PM [ Server Tick #27865, SourceTV:NoCheatZ-autorecords/de_nightfever-09-26-2016_03-14-37 PM.dem : Tick #27123 ] EyeAnglesTester triggered a detection : Son1c [[U:1:81136827] - 46.39.162.191:27005] is using a No recoil.
09/26/2016 03:21:24 PM [ Server Tick #27865, SourceTV:NoCheatZ-autorecords/de_nightfever-09-26-2016_03-14-37 PM.dem : Tick #27123 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.248235,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : -16.217794,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : -0.011848,
:::::::::::: Detections Count : 1d
:::::::: }
:::: }

09/26/2016 03:21:24 PM [ Server Tick #27867, SourceTV:NoCheatZ-autorecords/de_nightfever-09-26-2016_03-14-37 PM.dem : Tick #27125 ] EyeAnglesTester triggered a detection : Hawkeye [[U:1:26691495] - 89.103.71.138:27005] is using a No recoil.
09/26/2016 03:21:24 PM [ Server Tick #27867, SourceTV:NoCheatZ-autorecords/de_nightfever-09-26-2016_03-14-37 PM.dem : Tick #27125 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 2.304859,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : -15.115428,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : -0.003269,
:::::::::::: Detections Count : 1d
:::::::: }
:::: }

09/26/2016 03:33:12 PM [ Server Tick #75063, SourceTV:NoCheatZ-autorecords/de_nightfever-09-26-2016_03-14-37 PM.dem : Tick #74321 ] EyeAnglesTester triggered a detection : LJ. [[U:1:47834221] - 89.176.148.19:27005] is using a No recoil.
09/26/2016 03:33:12 PM [ Server Tick #75063, SourceTV:NoCheatZ-autorecords/de_nightfever-09-26-2016_03-14-37 PM.dem : Tick #74321 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 37.764244,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 60.060997,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000376,
:::::::::::: Detections Count : 1d
:::::::: }
:::: }

09/26/2016 03:38:05 PM [ Server Tick #18762, SourceTV:NoCheatZ-autorecords/fy_buzzkill_css-09-26-2016_03-33-31 PM.dem : Tick #18272 ] EyeAnglesTester triggered a detection : Pippi [[U:1:237123477] - 89.24.173.57:27005] is using a No recoil.
09/26/2016 03:38:05 PM [ Server Tick #18762, SourceTV:NoCheatZ-autorecords/fy_buzzkill_css-09-26-2016_03-33-31 PM.dem : Tick #18272 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 3.165608,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : -131.736664,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : -0.000000,
:::::::::::: Detections Count : 1d
:::::::: }
:::: }

09/26/2016 03:47:33 PM [ Server Tick #14403, SourceTV:NoCheatZ-autorecords/$2000$-09-26-2016_03-44-06 PM.dem : Tick #13851 ] EyeAnglesTester triggered a detection : Ironbounder [[U:1:107289881] - 81.200.60.233:27005] is using a No recoil.
09/26/2016 03:47:33 PM [ Server Tick #14403, SourceTV:NoCheatZ-autorecords/$2000$-09-26-2016_03-44-06 PM.dem : Tick #13851 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.019932,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 171.943222,
:::::::::::: Detections Count : 0d
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.011366,
:::::::::::: Detections Count : 1d
:::::::: } :::: }

```
