### ISSUE TITLE
Cant compile Nocheat. Error in make-protobuf.sh

### ISSUE THREAD

**Issue by Sandman007** [L-EARN/NoCheatZ-4#9]
I can not complile this on Ubuntu 14.04. There is no configure file and hence ./configure does not work

`make[1]: Entering directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin'
../scripts/make-protobuf.sh: 3: cd: can't cd to ./SourceSdk/Interfaces/Protobuf/protobuf-2.5.0
Updating protobuf 2.5.0
make[2]: Entering directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin'
Error : No target specified (debug, release, clean, superclean)
make[2]: *** [error] Error 1
make[2]: Leaving directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin'
Configuring protobuf 2.5.0
chmod: cannot access \u2018autogen.sh\u2019: No such file or directory
../scripts/make-protobuf.sh: 13: ../scripts/make-protobuf.sh: ./autogen.sh: not found
../scripts/make-protobuf.sh: 14: ../scripts/make-protobuf.sh: ./configure: not found
Building protobuf 2.5.0
make[2]: Entering directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin'
Error : No target specified (debug, release, clean, superclean)
make[2]: *** [error] Error 1
make[2]: Leaving directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin'
make[1]: *** [prepare-build] Error 2
make[1]: Leaving directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin'
make: *** [debug] Error 2
make[1]: Entering directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin'
../scripts/make-protobuf.sh: 3: cd: can't cd to ./SourceSdk/Interfaces/Protobuf/protobuf-2.5.0
Updating protobuf 2.5.0
make[2]: Entering directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin'
Error : No target specified (debug, release, clean, superclean)
make[2]: *** [error] Error 1
make[2]: Leaving directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin'
Configuring protobuf 2.5.0
chmod: cannot access \u2018autogen.sh\u2019: No such file or directory
../scripts/make-protobuf.sh: 13: ../scripts/make-protobuf.sh: ./autogen.sh: not found
../scripts/make-protobuf.sh: 14: ../scripts/make-protobuf.sh: ./configure: not found
Building protobuf 2.5.0
make[2]: Entering directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin'
Error : No target specified (debug, release, clean, superclean)
make[2]: *** [error] Error 1
make[2]: Leaving directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin'
make[1]: *** [prepare-build] Error 2
make[1]: Leaving directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin'
make: *** [debug] Error 2
`

**Comment by L-EARN** [comment]
Hi,

This is something I forgot to say in the readme.

You can safely remove the SourceSdk/Interfaces/Protobuf/Protobuf-2.5.0 directory.
Then, download and extract a fresh new protobuf SourceCode archive from here : https://github.com/google/protobuf/releases/tag/v2.5.0 (Download links are at the foot of the page)

I may update the make-protobuf.sh to detect if autogen is missing and then autocamitcally wget it ...

Thanks for posting this issue.

Tell me if this is ok for you next.

**Comment by Sandman007** [comment]
Ok So I did as you suggested. I ran sudo make release and received errors. Here is the last part of the console output that seems relevant:

`touch unittest_proto_middleman
make  all-am
make[5]: Entering directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0/src'
/bin/bash ../libtool  --tag=CXX   --mode=link g++ -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare  -m32 -DNDEBUG -version-info 8:0:0 -export-dynamic -no-undefined -m32 -o libprotobuf-lite.la -rpath /usr/local/lib atomicops_internals_x86_gcc.lo atomicops_internals_x86_msvc.lo common.lo once.lo stringprintf.lo extension_set.lo generated_message_util.lo message_lite.lo repeated_field.lo wire_format_lite.lo coded_stream.lo zero_copy_stream.lo zero_copy_stream_impl_lite.lo -lpthread 
libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib32/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.8/32/crtbeginS.o  .libs/atomicops_internals_x86_gcc.o .libs/atomicops_internals_x86_msvc.o .libs/common.o .libs/once.o .libs/stringprintf.o .libs/extension_set.o .libs/generated_message_util.o .libs/message_lite.o .libs/repeated_field.o .libs/wire_format_lite.o .libs/coded_stream.o .libs/zero_copy_stream.o .libs/zero_copy_stream_impl_lite.o   -lpthread -L/usr/lib/gcc/x86_64-linux-gnu/4.8/32 -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../i386-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib32 -L/lib/i386-linux-gnu -L/lib/../lib32 -L/usr/lib/i386-linux-gnu -L/usr/lib/../lib32 -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/4.8/32/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib32/crtn.o  -pthread -m32 -m32   -pthread -Wl,-soname -Wl,libprotobuf-lite.so.8 -o .libs/libprotobuf-lite.so.8.0.0
libtool: link: (cd ".libs" && rm -f "libprotobuf-lite.so.8" && ln -s "libprotobuf-lite.so.8.0.0" "libprotobuf-lite.so.8")
libtool: link: (cd ".libs" && rm -f "libprotobuf-lite.so" && ln -s "libprotobuf-lite.so.8.0.0" "libprotobuf-lite.so")
libtool: link: ar cru .libs/libprotobuf-lite.a  atomicops_internals_x86_gcc.o atomicops_internals_x86_msvc.o common.o once.o stringprintf.o extension_set.o generated_message_util.o message_lite.o repeated_field.o wire_format_lite.o coded_stream.o zero_copy_stream.o zero_copy_stream_impl_lite.o
libtool: link: ranlib .libs/libprotobuf-lite.a
libtool: link: ( cd ".libs" && rm -f "libprotobuf-lite.la" && ln -s "../libprotobuf-lite.la" "libprotobuf-lite.la" )
make[5]: Leaving directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0/src'
make[4]: Leaving directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0/src'
make[3]: Leaving directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0'
make[2]: Leaving directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0'
make[1]: Leaving directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin'
make[1]: Entering directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin'
 Code/plugin.cpp =>  Release/Code/plugin.o
make[1]: *** [Release/Code/plugin.o] Error 1
make[1]: Leaving directory `/home/tyler/Desktop/NoCheatZ-4/server-plugin'
make: *** [release] Error 2
`

**Comment by Sandman007** [comment]
**<script src="//pastebin.com/embed_js/bvZEuXiG"></script>**

**Comment by Sandman007** [comment]
[<script src="//pastebin.com/embed_js/bvZEuXiG"></script>](url)

**Comment by Sandman007** [comment]
Full Output: http://pastebin.com/bvZEuXiG

**Comment by L-EARN** [comment]
When compiling the plugin, errors of the compiler will go into server-plugin/error-compile.txt.
I would like to get the output of this file, please.

Note the linker errors will go into server-plugin/error-link.txt

**Comment by Sandman007** [comment]
**https://app.box.com/s/gr4hubdd3izg2m864y9ilh5o1vy51u2s**

**Comment by Sandman007** [comment]
Error-Compile.txt

https://app.box.com/s/gr4hubdd3izg2m864y9ilh5o1vy51u2s

**Comment by L-EARN** [comment]
This is should be fixed in https://github.com/L-EARN/NoCheatZ-4/commit/5e0b35a503832b3c06a860441d1f64bf0fd40d8b

I suggest you pull down the lastest commit on master and you try building again.

**Comment by Sandman007** [comment]
Ok I got a successful build! Sorry it took me so long to get back to you. I was the only IT guy at work yesterday afternoon and I was swamped! 

Anyways, I have a question. I am used to putting a plugin (pluginname.smx) into the plugins folder. Obvisously this one is different. i have the NoCheatZ Dir and the nocheatz.vdf in my csgo_arena/csgo/addons/ Directory, I assume this is correct? Since there is no .smx it won't show in my sm plugins list output in console. How do I know if it is really loaded and is working properly?

Thanks for your help yesterday!

**Comment by L-EARN** [comment]
This is not a SourceMod nor a MetaMod:Source plugin.
NoCheatZ is standalone, it's a Valve Server Plugin.

If you want to see the plugins loaded as VSPs, you can use the command : plugin_print

More informations here : https://developer.valvesoftware.com/wiki/Server_plugins (first chapter) 

After that, you can also print the status of the current subsystems using ncz (Note this will not pop up in rcon, you need to have direct access to the server console to see the output)

**Comment by Sandman007** [comment]
Ok So I did plugin_print (I have direct access to the console) and only Metamod:Source is listed. Did I install something incorrectly?

**Comment by L-EARN** [comment]
Ok I tested on a CSGO server with a release build and I got the same think.

Here is all the erros in the latest commit :

* The Logger::Msg<MSG_ERROR> doesn't print the error.
* The Makefile doesn't copy config.ini in the Builds directory so ConfigManager can't load the file and the plugin can't load even if you copy the builds directory to your gameserver
* When the plugin is not correctly loaded, the engine calls Unload, but this could crash because Unload is deleting invalid pointers at this state. (That's why your server reboots)

You should still be able to run the server by copying the `NoCheatZ-4/server-plugin/Res/config.ini` file into `csgo/addons/NoCheatZ/` directory while I fix all of that.

**Comment by Sandman007** [comment]
Ok! It is now loading correctly! I really appreciate you helping me out. I have one more question for you and then I will leave you alone :P

In nocheats.cfg located in csgo/cfg What do the below commented lines do and can I uncomment them?

// Virtual Tables offsets (For Linux)
//ncz_onground_offset 179
//ncz_runcommand_offset 420
//ncz_settransmit_offset 21
//ncz_teleport_offset 109
//ncz_weaponequip_offset 262
//ncz_weapondrop_offset 264

Thanks!

**Comment by L-EARN** [comment]
These are deprecated convars. You better remove the lines. If you uncomment you'll see errors in your console, but it will not crash.

Configuration of virtual tables are now in config.ini.
You may not change them until source engine updates to the point it brokes them.
If it ever happens, you could update offsets yourself using our levoly friends from the SourceMod team : https://www.sourcemodplugins.org/vtableoffsets
(Note CS:S offsets are wrong in this webpage)

But now don't take care about that.
