### ISSUE TITLE
You can't join the game now because your Steam ID is not validated yet

### ISSUE THREAD

**Issue by musosoft** [L-EARN/NoCheatZ-4#91]
Majority of players are not able to connect to our CS:S server while ValidationTester is enabled:

```
Retry with the F9 button or activate Steam and restart the game.
You can't join the game now because your Steam ID is not validated yet
```

Please see attached ncz log

[NoCheatZ-26-Sep-2016.log.txt](https://github.com/L-EARN/NoCheatZ-4/files/493087/NoCheatZ-26-Sep-2016.log.txt)

**Comment by L-EARN** [comment]
Do you use a non-steam server or not ?

**Comment by musosoft** [comment]
Sorry for late-reply. I am using steam server

**Comment by L-EARN** [comment]
I will try to rework this system.

In the meantime you can disable it, it's not the most important one to enable, valve fixed the issue covered by this system already if I remember.
